### ISSUE TITLE
Verification code is empty, please enter the verification code-Can not Login with email

### ISSUE THREAD

**Issue by Lekinio** [szdc/tiktok-api#100]
when  i trying to login with email,it shows me this error

> { data:
   { captcha: 'R0lGODlheQAoAIcAAAAAAAAARAAAiAAAzABEAABERABEiABEzACIAACIRACIiACIzADMAADMRADMiADMzADd3REREQAAVQAAmQAA3QBVAABVVQBMmQBJ3QCZAACZTACZmQCT3QDdAADdSQDdkwDungDu7iIiIgAAZgAAqgAA7gBmAABmZgBVqgBP7gCqAACqVQCqqgCe7gDuAADuTwD/VQD/qgD//zMzMwAAdwAAuwAA/wB3AAB3dwBduwBV/wC7AAC7XQC7uwCq/wD/AEQAREQAiEQAzEREAEREREREiEREzESIAESIRESIiESIzETMAETMRETMiETMzEQAAFUAAFUAVUwAmUkA3VVVAFVVVUxMmUlJ3UyZAEyZTEyZmUmT3UndAEndSUndk0nd3U/u7mYAAGYAZlUAqk8A7mZmAGZmZlVVqk9P7lWqAFWqVVWqqk+e7k/uAE/uT0/unlX/qlX//3cAAHcAd10Au1UA/3d3AHd3d11du1VV/127AF27XV27u1Wq/1X/AFX/VYgAiIgAzIhEAIhERIhEiIhEzIiIAIiIRIiIiIiIzIjMAIjMRIjMiIjMzIgAAIgARJkATJkAmZMA3ZlMAJlMTJlMmZNJ3ZmZAJmZTJmZmZOT3ZPdAJPdSZPdk5Pd3ZkAAKoAAKoAVaoAqp4A7qpVAKpVVapVqp5P7qqqAKqqVaqqqp6e7p7uAJ7uT57unp7u7qr//7sAALsAXbsAu6oA/7tdALtdXbtdu6pV/7u7ALu7Xbu7u6qq/6r/AKr/Var/qswAzMxEAMxERMxEiMxEzMyIAMyIRMyIiMyIzMzMAMzMRMzMiMzMzMwAAMwARMwAiN0Ak90A3d1JAN1JSd1Jk91J3d2TAN2TSd2Tk92T3d3dAN3dSd3dk93d3d0AAN0ASe4AT+4Anu4A7u5PAO5PT+5Pnu5P7u6eAO6eT+6enu6e7u7uAO7uT+7unu7u7u4AAP8AAP8AVf8Aqv8A//9VAP9VVf9Vqv9V//+qAP+qVf+qqv+q////AP//Vf//qv///ywAAAAAeQAoAAAI//8EDiRY0KBBGwkPLmQoMOFDiBElTqTY0OJFjBk1buTY0eNHhDZAjiRZ0iTCjA9PhlS40qVGlSgdvmQZ0WRMmg4hyvwn8uBElxI72szZc2dBnz1hUgSKkehSnDSfEowatCnVo1BbFq1a9ONTXppWdbPY1WtRd2nTft3qLg+aPHF5uTu7shuvVas2utMEVy7BbpryrNLES6M7G7zw/q1bclXcPEkx8rUxOC7Zf24ho9GbkRcauv+62QhNcG1jjJ9trFKMBnPGboPd8ZL97/HcVZwzag5N27BpyLxeozb4OY+7u5F/U22Y27DguXk0zY5b2qI7NIYNx16eObd0yMQNxv8+Tj7PXJ4HY0+n/fi87feeSf9DMz07wcd6k+cxiRx9xse6IW8u6zRy7p++Evvns84API6XyrBrELFV1nKrQo9mmyustyRriDy+OAuLtY6wexCutKo7TLZVbChMOrpCFFAgxIbTyDwb0FgNutTOwy5HHRPCcKPPtOvGnQMPUzCy42RDUkQYP7MxNbiEW0+x+CzqBrTR6ouoQY1UXJCzAi36LEU00KCPPwZpIzOuEqvj6685U/OpMAgjKtOiJJPcDU43s3uMNwhdw647z97rK67snqQyrc+CfIhMJYcscq/73MuDPOhUY3M+jj7LTEH6KsxtSoMOvMwokaRD9SDeEKT/S0w7Zz3PtQ6xTFOvQTuqbsvfqvPtotv+qe1CJLM08z4I+UPsP2LLGwxCJCszFrIjKeXI1WHhow7Rg4oVLEZAN50MrszSnK/F3cj0jTva7uIMzmc9qjI2pvLVV0+MNFmXNHRNnCyxZL/NjLbz3jvzIx8fEwhY29S8qEjN3EuRv/REU7BeCMmiduLNMLaBLN4C1AykKFcLbF3XLjpZM0VbRqqtt9AciF44J3bPMGRbnHW6Q1E2N7ccFVaWoS1BQy45bZEiqFlGlzPuMQ+vo5HRwURLeU/Y5Jyrm0FjG7Ih6ioD72ikCZNu7GTD82ixsagz9biREGbtsV3r3G2xwl4tVVEtrnfrDTKCSYIZrhYNY9ejfat2eaXZLD7prtBki1c8zAfymyRh0c7885PABX100ks3/XSWbtoKddSmYnwgx1nPyfWhYJe99ay+sv32xswaanWSAgIAOw==',
     description: 'Verification code is empty, please enter the verification code.',
     error_code: 1101 },
  message: 'error' }

**Comment by klliks-com** [comment]
I need the same help with captcha.
I don't understand how to solve manually.

@szdc why are you deleting my message? i need to understand how i can solve captcha i have small amount of acounts.

**Comment by klliks-com** [comment]
@szdc why you acting like a bully? why is it so hard for people to be nice?
I am not spamming and not abusing. i need help and people here can help me.

You don't want to help - i don't understand why, but it's your life.
Let others help each other. stop being a fucker.

**Comment by Pilfer** [comment]
It's a base64-encoded image. Prepend `data:image/png;base64,` to it and you can render it via HTML (try it out here: https://www.site24x7.com/tools/datauri-to-image.html).

Solve the captcha (`q6xm`) and log in again with the `captcha` field populated with the captcha solution.

**Comment by Lekinio** [comment]
thanks,its worked

**Comment by romeoaaron21** [comment]
@Pilfer How can I use the captcha solution in logging in again?
