### ISSUE TITLE
Captcha solve manually

### ISSUE THREAD

**Issue by klliks-com** [szdc/tiktok-api#101]
Hi Guys,

I need help to understand how can i solve the captcha manually?
The only thing i was thinking is to wrap it around APK but it's a lot of work.

Can i get clear explanations on captcha solver for this new puzzle?

@szdc please help me, we are in production.

**Comment by Pilfer** [comment]
Open your MiTM application and log the requests. Look at the parameters being sent. Emulate those parameters and you're golden.

**Comment by klliks-com** [comment]
> Open your MiTM application and log the requests. Look at the parameters being sent. Emulate those parameters and you're golden.

Please share with me your contact. i will pay for your time.
I am working on latest version and have done MiTM and have all dumps.

I still not able to solve/login

**Comment by szdc** [comment]
Please stop opening issues, this is not within the scope of this repository.
