### ISSUE TITLE
api.listPosts(params) return undefined

### ISSUE THREAD

**Issue by marcosvalbonet** [szdc/tiktok-api#103]
When I am trying to list posts, api return me undefined. 

I call to api with the next code:
api.listPosts({
  user_id: '<user_id>',
  max_cursor: 10,})

As you can think, I add a <user_id>.
Has something changed in the api?

**Comment by Bodicj** [comment]
I had the same issue with this method. Have you got any solution?

**Comment by kamyweb** [comment]
Same issue

**Comment by kamyweb** [comment]
I don't know why, but if you change the device_type works - ex. :
`params.device_type = 'EML-L29';`
after getRequestParams and before instance TikTokAPI class.

**Comment by timbilino** [comment]
Same error, sorry, any answer?

**Comment by timbilino** [comment]
> I don't know why, but if you change the device_type works - ex. :
> `params.device_type = 'EML-L29';`
> after getRequestParams and before instance TikTokAPI class.

it didn't work out for me :(

**Comment by hrehman200** [comment]
@kamyweb answers works, but you will need to change device_type to device model on which you installed Tiktok app and used it for a while e.g. I installed Tiktok on Samsung Galaxy J7 Prime (SM-G610F), I changed device_type in code from 'Pixel' to 'SM-G610F' and listPosts function is now returning posts.

**Comment by alpharameeztech** [comment]
@hrehman200 @timbilino. I don't understand that. In order to search and list the post of the user on my web application, I first need to install tiktok app on my mobile phone and then get params.device_type for the web application to run?

**Comment by hrehman200** [comment]
Well thats how it worked. Tiktok doesn't appreciate you call their api from web. So we have to try various hacks to get things done.

I could login and search users. But listing posts of a user wasn't working. I tried various things. In the end the solution I described above worked for listing posts. 

For other api calls, we still have to deal with spam parameters I guess.

**Comment by alpharameeztech** [comment]
@hrehman200 thankyou for your reply, much appreciated. Okay, so now I have to install the tiktok app on my phone but titkok won't display the device information needed by the API. How can I make it work?

**Comment by hrehman200** [comment]
As mentioned by author of this repo:
```
// Required - device parameters
// You need to source these using a man-in-the-middle proxy such as mitmproxy,
// CharlesProxy or PacketCapture (Android)
```

**Comment by alpharameeztech** [comment]
@hrehman200 thanks a bunch. I am going it give it a try on iPhone

**Comment by hrehman200** [comment]
Ok please update this thread with your findings.

**Comment by alpharameeztech** [comment]
@hrehman200 Once I launch Packetcapture, the internet stopped to work and then it doesn't load anything on tiktok ofcourse

**Comment by hrehman200** [comment]
Yeah i noticed it too today. Last time it worked. Now will have to find
another way.

**Comment by alpharameeztech** [comment]
@hrehman200 let us know if you find one. Thanks alot :)

**Comment by hrehman200** [comment]
So the other way is:
- You jailbreak your iPhone
- Use SSL Kill Switch to bypass SSL Pinning
- Use burp to capture requests

I didn't do these things myself, but a colleague of mine did and he shared with me request / response.

**Comment by alpharameeztech** [comment]
@hrehman200 thank you for your effort, much appreciated :)

**Comment by szdc** [comment]
Closing as this project is no longer maintained.
