### ISSUE TITLE
[Question] Legality

### ISSUE THREAD

**Issue by BaderSerhan** [szdc/tiktok-api#110]
I would like to know the legality of using this in my app. Have you had any legal issues or concerns with the TikTok people regarding this? And do you have any examples of products/companies using this library? I would like to see it in action and inquire about the legality of embedding this in my app.

Thank you in advance to anyone who responds!

**Comment by szdc** [comment]
No concerns have been raised. No examples. Don't use this library to create bots or anything similar.
