### ISSUE TITLE
aweme/v1/aweme/detail/?aweme_id endpoint gone?

### ISSUE THREAD

**Issue by sp0oon** [szdc/tiktok-api#116]
Until recently I was able to use the "aweme/v1/aweme/detail/?aweme_id=" but it seems like it's no longer working as of a few days ago?

Is anyone else having the same issue?

**Comment by PeterPorzuczek** [comment]
Probably because of this https://research.checkpoint.com/2020/tik-or-tok-is-tiktok-secure-enough/

**Comment by KanaiyaKatarmal** [comment]
This api is working in my case.

I have got the solutions.

**Comment by kienvtqhi** [comment]
> This api is working in my case.
> 
> I have got the solutions.

Hello Kanaiya, can you share your solutions? I am facing the same issue. Thank you so much!

**Comment by szdc** [comment]
Closing as this project is no longer maintained.
