### ISSUE TITLE
How can I get device info from the API call through web app

### ISSUE THREAD

**Issue by alpharameeztech** [szdc/tiktok-api#117]
I don't understand that. In order to search the user and list the post of the user on my web application, I first need to install tiktok app on my mobile phone and then get params.device_type for the web application to run? How can I make it work with this API?

**Comment by alpharameeztech** [comment]
How can I verify my device from the web API?

**Comment by hrehman200** [comment]
You can't, you need to use real device_id.

**Comment by husligc** [comment]
Is this working for anyone?

**Comment by PJ-G** [comment]
Would we be able to get the device_id through the iOS app? All suggestions point to breaking down APKs of Android Apps. Or better yet is there a list of endpoint's and authentication methods so I could write my own implementations?

**Comment by mastercho** [comment]
I saw peoples invent API generators for device fingerprint, but not sure how they manage to do it.

**Comment by szdc** [comment]
Closing as this project is no longer maintained.
