### ISSUE TITLE
fp (finger print) query string parameter seems is no longer existing in recent login related MITM capture

### ISSUE THREAD

**Issue by atwleung** [szdc/tiktok-api#119]
**Describe the bug**

fp is one param required in getRequestParams. However, in recent MITM capture, I no longer sees the parameter. So users of tiktok-api can no longer supply the value of this parameter

**To Reproduce**
A small example of code that reproduces the bug.

I can share the MITM capture via private messages.

**Expected behavior**

I would expect the tiktok-api no longer requiring users to provide fp parameter and its value.

**Additional context**

**Comment by honeydewlover** [comment]
Your expected behavior is correct, I have the same results.

**Comment by szdc** [comment]
Thanks.  I haven't updated this repository for a while so will take a look when I can.

**Comment by KlliksMarketing** [comment]
@szdc Anything new on deviceID and InstallID ?

**Comment by reteps** [comment]
@szdc any updates? It appears a bot using the TikTok api was written in PHP over [here](https://github.com/snuzi/tiktok-scraper-php), maybe they are using a more recent TikTok api.

**Comment by szdc** [comment]
Closing as this project is no longer maintained.
