### ISSUE TITLE
The postComment method is not working for me

### ISSUE THREAD

**Issue by asymness** [szdc/tiktok-api#121]
The postComment method in the API is not working for me. The response includes a success status code and and a status message stating "Comment sent successfully.", however the comment does not appear on the post. Can someone else try and see if they can reproduce this problem?

**To Reproduce**
1. call the postComment api method with a post ID and a comment text.
2. Check the post manually to see if the comment appears on the post or not.

**Expected behavior**
The comment should appear on the post. (I tried on posts with 0 comments)

**Desktop (please complete the following information):**
 - OS: Windows
 - Node: Version 10.16.3

**Additional context**
I tried from 2 different accounts, and the likePost and follow methods are working for me.

**Comment by Dimabytes** [comment]
Did you solve it? I had the same issue

**Comment by szdc** [comment]
Closing as this project is no longer maintained.
