### ISSUE TITLE
Are the current docs correct? Seems to not work

### ISSUE THREAD

**Issue by Amirh24** [szdc/tiktok-api#122]
**Describe the bug**
API not working following the current docs (inserting 3 anti-spam parameters and device parameters)

**To Reproduce**
Follow the docs to call the API

**Expected behavior**
It should work

**Additional context**
I see that others are experiencing the same behavior and it a result of a TikTok internal change

**Comment by szdc** [comment]
Probably not as I haven't updated the API in 10 months.

**Comment by beshoo** [comment]
@szdc is this the end of life for this API ?

**Comment by design365** [comment]
[root@kind-wall-2 tiktok-js]# node test.js
(node:22902) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
/data/run/tiktok-js/test.js:1
import TikTokAPI, { getRequestParams } from 'tiktok-api';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (internal/modules/cjs/loader.js:1055:16)
    at Module._compile (internal/modules/cjs/loader.js:1103:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1159:10)
    at Module.load (internal/modules/cjs/loader.js:988:32)
    at Function.Module._load (internal/modules/cjs/loader.js:896:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47

**Comment by davidteather** [comment]
Tiktok changed quite a bit to their api last month that probably broke this one. I don't have all the same functionality in my module, but you can get TikTok json objects and download videos and more.

[TikTok-Api](https://github.com/davidteather/TikTok-Api)

**Comment by szdc** [comment]
Closing as this project is no longer maintained.
