### ISSUE TITLE
Is there any way to download videos or copy the share link? This would be a nice feature

### ISSUE THREAD

**Issue by DroScope** [szdc/tiktok-api#131]
Sorry, this is my first comment, just suggesting a download/copy link option. Thanks!

**Comment by BenjaminMueggenburg** [comment]
Here's an example where you can get the `share_url`

```JavaScript
// Login... setup api
api.getPost('<user_id>')
  .then(res => console.log(res.data.share_url))
  .catch(console.log);
```

**Comment by szdc** [comment]
Adding to the comment above, the download link is available at `res.data.video.download_addr` ([ref](https://github.com/szdc/tiktok-api/blob/master/src/types/video.d.ts#L8))
