### ISSUE TITLE
fake people use this app who  is already dead and i want to report because its like you are insulting and crossing the limits of privacy policy 

### ISSUE THREAD

**Issue by mylocalcoin** [szdc/tiktok-api#133]
**Describe the bug**
@nerryyadav tiktok id is already r.i.p and you were promoting dead person and its against the privacy policy 

**To Reproduce**
A small example of code that reproduces the bug.

**Expected behavior**
r.i.p person reported and fake community generated huminity act

**Additional context**

**Comment by szdc** [comment]
I don't know what you're talking about.

**Comment by breadadams** [comment]
![image](https://user-images.githubusercontent.com/5795227/82001193-e6b3fd80-965a-11ea-8fbf-e97653335044.gif)
