### ISSUE TITLE
Can not get parameter. Please explain for us this parameter

### ISSUE THREAD

**Issue by cuongsapi** [szdc/tiktok-api#138]
Please explain for me this parameter here. How to create it. 
const params = getRequestParams({ device_id: '<device_id>', fp: '<device_fingerprint>', iid: '<install_id>', openudid: '<device_open_udid>', });

**Comment by CesarIAndrade** [comment]
**iid** =  The 16-character ID of your installation, I mean the installation id of **Tiktok** in your phone, e.g. 4549764744226841084 (you could obtain it using **Http Canary**, an android app - Note: You need to be **root**) 
**openudid** = A 16-character hexadecimal identifier associated with your device, e.g. 4b903fbb9d457937 (you can easily find it using **Device ID**, another android app)
**device_id** = The ID of your device that has already been registered with musical.ly (once again, you could obtain it using **Http Canary**, an android app - Note: You need to be **root**) 
**fp** = An anti-fraud fingerprint of your device requested from a different API (you can easily find it using **Device ID**)

**Comment by 350d** [comment]
Is that possible to fake all of these params? Like random iid, device_id etc?

**Comment by mrklintscher** [comment]
@350d no it isnt. It must be a valid registered device.

**Comment by keldermen** [comment]
@CesarIAndrade Thanks for the information I have been able to get the iid, openudid and device_id with http canary. But I have no how to get the fingerprint. Can you help me with that?

**Comment by duylinhdang1998** [comment]
How I can get this and use api ? I dont understand

**Comment by pamanbobb** [comment]
where i can found.

const as = 'anti-spam parameter 1';
const cp = 'anti-spam parameter 2'
const mas = 'anti-spam parameter 3';

as , cp and mas. please help

**Comment by szdc** [comment]
Closing as this project is no longer maintained.
