### ISSUE TITLE
Upload Video

### ISSUE THREAD

**Issue by pankixoi2113** [szdc/tiktok-api#141]
Has anyone tried to upload a video? When I try to download, I get an error {"code":400,"error":"MismatchChecksum","message":"mismatch checksum"}}

**Comment by tonyquang** [comment]
try using selenium to upload video!

**Comment by AndrewGrinev** [comment]
> Has anyone tried to upload a video? When I try to download, I get an error {"code":400,"error":"MismatchChecksum","message":"mismatch checksum"}}

How do you upload a video?

**Comment by g3luka** [comment]
How do you post a video?
What method do I use and what is the process?

**Comment by spryka** [comment]
Does anyone have succed with uploading video?

**Comment by mrklintscher** [comment]
Yes i can do.

Write me here me@mrklintscher.de

**Comment by dyanakiev** [comment]
Has anyone managed to upload a video?

**Comment by cnscorpions** [comment]
I am also interested in uploading videos, and guess that automation tools like puppeteer or playwright need to be used. 😁

**Comment by Lg0gs** [comment]
@libfintx 
Can you help me there?

**Comment by szdc** [comment]
Closing as this project is no longer maintained.
