### ISSUE TITLE
Video views count

### ISSUE THREAD

**Issue by Ariel042cohen** [szdc/tiktok-api#142]
Do you know how can I get video views count? I only see on the api likes count, shares count and comment count.

**Comment by arsalyou** [comment]
Hello,
Can you provide me sample parameters which you supplied in here?

const signURL = async (url, ts, deviceId) => {
  const as = 'anti-spam parameter 1';
  const cp = 'anti-spam parameter 2'
  const mas = 'anti-spam parameter 3';
  return `${url}&as=${as}&cp=${cp}&mas=${mas}`;
}

// Required - device parameters
// You need to source these using a man-in-the-middle proxy such as mitmproxy,
// CharlesProxy or PacketCapture (Android)
const params = getRequestParams({
  device_id: '<device_id>',
  fp: '<device_fingerprint>',
  iid: '<install_id>',
  openudid: '<device_open_udid>',
});

**Comment by szdc** [comment]
Closing as this project is no longer maintained.
