### ISSUE TITLE
How can I implement these APIs Android ?

### ISSUE THREAD

**Issue by arsalyou** [szdc/tiktok-api#143]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Additional context**
Add any other context here.

**Comment by akash09766** [comment]
how can i use this api as rest api in android/ios

**Comment by PierreAndreis** [comment]
This package should be used by your backend which then should provide you an API to use it.

**Comment by Mokin711** [comment]
Is it possible to add it on firebase function and then implement this to the ios/android app? I am a front end developer and have no experience in backend so I am curious about the solution to the question as well

**Comment by thecherrie** [comment]
> This package should be used by your backend which then should provide you an API to use it. Or you can use in the client and ask the user to type in their credentials

Bro what do you mean?

**Comment by szdc** [comment]
Closing as this project is no longer maintained.
