### ISSUE TITLE
Smaller resolution videos available?

### ISSUE THREAD

**Issue by tokjii** [szdc/tiktok-api#145]
I'm getting videos by making requests from `https://www.tiktok.com/share/item/list?secUid=&id=&type=5[...]`. Many videos are 1280x720 but I need way less than that. Instagram's API response has return numerous video links for different screen dimensions. Does TikTok offer something similar?

**Comment by tokjii** [comment]
Spoofing the user agent also didn't work for me

**Comment by szdc** [comment]
Closing as this project is no longer maintained.
