### ISSUE TITLE
Get Users Likes

### ISSUE THREAD

**Issue by swaglogger** [szdc/tiktok-api#146]
**Describe the solution you'd like**
Grab the links of a user's likes. I like posts on my account on my phone but then want to grab the links through the api to download. Users likes can be public/private based on account settings

**Comment by XHL-Mao** [comment]
> **Describe the solution you'd like**
> Grab the links of a user's likes. I like posts on my account on my phone but then want to grab the links through the api to download. Users likes can be public/private based on account settings

Hello, Do you know how to do it？

**Comment by swaglogger** [comment]
No this is a request to get it added

**Comment by sourabhbagrecha** [comment]
@swaglogger is this API still working? Most of my requests (almost all) are getting failed, with data as an empty string in the response ( { data: "" } ).

**Comment by szdc** [comment]
Closing as this project is no longer maintained.
