### ISSUE TITLE
Unable to use mitmproxy to intercept traffic to/from Tiktok

### ISSUE THREAD

**Issue by JoeHO888** [szdc/tiktok-api#147]
**Describe the bug**
After I connect to Wifi with mitmproxy proxy, I cannot connect to Tiktok App.
![WhatsApp Image 2020-02-22 at 3 51 58 PM](https://user-images.githubusercontent.com/29224653/75088664-6fa32780-558b-11ea-93f7-c43386047f4f.jpeg)

**To Reproduce**
Follow this [article](https://medium.com/@szdc/reverse-engineering-the-musical-ly-api-662331008eb3)

**Expected behavior**
I should be able to see HTTP Traffic in mitmproxy shell

**Additional context**
I understand that it is not a bug of this piece of software, but I cannot find a good channel to contact with author @szdc directly.

**Comment by skattex** [comment]
you need to have root permission on your device. And after application, such as mitmproxy, packetcapture and other will work with ssl encryption.

**Comment by JoeHO888** [comment]
@skattex Thank you for your reply. I just rooted my device, but I still fail to intercept HTTP traffic with mitmproxy for Tiktok. mitmproxy is able to intercept other traffic when I try to browser other websites.

Able to intercept other traffic
![WhatsApp Image 2020-02-22 at 5 46 19 PM](https://user-images.githubusercontent.com/29224653/75090178-47bbc000-559b-11ea-9486-3557c243d970.jpeg)

Rooted Device
![WhatsApp Image 2020-02-22 at 5 48 03 PM](https://user-images.githubusercontent.com/29224653/75090198-7fc30300-559b-11ea-8a43-781b163be1a1.jpeg)

**Comment by Rh3x4r** [comment]
put cert file on root or use any android version which less than 7.0

**Comment by lalokupfer** [comment]
I use nox emulator which has older version of Android I think 5.x and I installed there the certificate and the latest TikTok, with fiddler as a proxy I was able to intercept the traffic...

**Comment by JoeHO888** [comment]
Yep, it has to be older version of Android & TikTok

**Comment by joostcore** [comment]
Any ideas how to fix this for future versions ?

**Comment by huuhuybn** [comment]
hello, have you fix problem yet ?

**Comment by szdc** [comment]
Closing as this project is no longer maintained.
