### ISSUE TITLE
How to answer the verification using captcha? : Verification code error, please re-enter the verification  code.

### ISSUE THREAD

**Issue by romeoaaron21** [szdc/tiktok-api#148]
{ data: 
   { captcha: 'R0lGODlheQAoAIcAAAAAAAAARAAAiAAAzABEAABERABEiABEzACIAACIRACIiACIzADMAADMRADMiADMzADd3REREQAAVQAAmQAA3QBVAABVVQBMmQBJ3QCZAACZTACZmQCT3QDdAADdSQDdkwDungDu7iIiIgAAZgAAqgAA7gBmAABmZgBVqgBP7gCqAACqVQCqqgCe7gDuAADuTwD/VQD/qgD//zMzMwAAdwAAuwAA/wB3AAB3dwBduwBV/wC7AAC7XQC7uwCq/wD/AEQAREQAiEQAzEREAEREREREiEREzESIAESIRESIiESIzETMAETMRETMiETMzEQAAFUAAFUAVUwAmUkA3VVVAFVVVUxMmUlJ3UyZAEyZTEyZmUmT3UndAEndSUndk0nd3U/u7mYAAGYAZlUAqk8A7mZmAGZmZlVVqk9P7lWqAFWqVVWqqk+e7k/uAE/uT0/unlX/qlX//3cAAHcAd10Au1UA/3d3AHd3d11du1VV/127AF27XV27u1Wq/1X/AFX/VYgAiIgAzIhEAIhERIhEiIhEzIiIAIiIRIiIiIiIzIjMAIjMRIjMiIjMzIgAAIgARJkATJkAmZMA3ZlMAJlMTJlMmZNJ3ZmZAJmZTJmZmZOT3ZPdAJPdSZPdk5Pd3ZkAAKoAAKoAVaoAqp4A7qpVAKpVVapVqp5P7qqqAKqqVaqqqp6e7p7uAJ7uT57unp7u7qr//7sAALsAXbsAu6oA/7tdALtdXbtdu6pV/7u7ALu7Xbu7u6qq/6r/AKr/Var/qswAzMxEAMxERMxEiMxEzMyIAMyIRMyIiMyIzMzMAMzMRMzMiMzMzMwAAMwARMwAiN0Ak90A3d1JAN1JSd1Jk91J3d2TAN2TSd2Tk92T3d3dAN3dSd3dk93d3d0AAN0ASe4AT+4Anu4A7u5PAO5PT+5Pnu5P7u6eAO6eT+6enu6e7u7uAO7uT+7unu7u7u4AAP8AAP8AVf8Aqv8A//9VAP9VVf9Vqv9V//+qAP+qVf+qqv+q////AP//Vf//qv///ywAAAAAeQAoAAAI//8EDiRY0OBBhAkVLmTYcKENiBEhOqRY0eI/Gxc1buTYUWPGjB5FjiS5MWRJlClVkpTY0uVKmDFlzqRZ0+ZNnDl17uTZE2VLhN14dXPn06E7pEh5upSIxkYeXj9LuuuWJ48NNGhWFfXJC02eVbyYSjQ5UWC3VWDDWlz1NSyvq3m47nRnQxNRXlHdtY1K8KXDjO7gfrVaeG5BswLFbhVa1N3XwzjbdqvqFA0vd1ZRwoWK+d9ezQmbahLs1AZjG90sKhWIlHJkhmAFQ80sF67qkXC3gpb7bzJDsUW//hMbNXTDvKu2CkxbuKJVzHlIE4data9Iq4KfakJzVzdD7khTC/+UTvzkwlVYnfa12hx3w7RILwuMWHUV4MQFu12ujTRtdE1iy+Ofbk7SRK4CHfIqKq2Kkq6094BDQ7yoTpMLogg7soq7AQmcz4brEjrwMxu40qwu2A5Ki6gG/8kOrhAXKlC1A8XSDCLWPIoLs9ku4wu4kCB7bEAU4ZuvOwe3gpGiqkjjDKsKz/NoLs7yECoPrTI0qK6ovLJMtQJTNOg/F6c7cLYYF/LKtrwiim+kiBQDsSi0NHmKockEUy4v8xwiM7t/DrwyTYV404Q7/soTCai60voKM93EbA1LTfK6irS2FIQq0A7j46XSi3hx9Ck04STLxUeh41TS1rhTb87jYrvv70zfrPyuIqEsLXFIlk6lyrERg2MoqcFKIxQhsGolSlD7KrKxMKLSY9WiOAUTalInrVxorwOxjK5Dh4ItTDrKkqUIxryQam+lbg6EclBlZcRKtszQ0FKhFWeT7q4mnwMruUenNemrqrAkNVI1U6PKy2MT4oxYLMGKFU/CsFwrJnr5LG3CYZ8yuLdQC+s2ok1xHYoomtbMlbO7ECIrs1UqFbjQtDRJT6K58jOqNUfH9Yyhv0wda2iix1IJqXQ70pkjoA5aemeapHzoab+gpi9qqq1WOuuSpNYazq/DFlumOMc2G7FTzz67abXNZpukgAAAOw==',
     captcha_key: '6594726280552547846',
     description: 'Verification code error, please re-enter the verification  code.',
     error_code: 1102 },
  message: 'error' }

**Comment by CesarIAndrade** [comment]
Could you solve it?

**Comment by tmswartz12** [comment]
Would love the answer here!

**Comment by kanfyti** [comment]
You can find the same problem and solution here: [https://github.com/szdc/tiktok-api/issues/100](url)

**Comment by colymore** [comment]
Just convert base64 to image (https://codebeautify.org/base64-to-image-converter) solve by yourself and add to the login call

const login = () => api.login({
  username: 'aa',
  email: 'ee',
  password: 'ii',
  captcha: 'ANY_CAPTCHA'
})

**Comment by mrklintscher** [comment]
You have to use opencv and solve it. Send the data back to tiktok.

**Comment by areltiyan** [comment]
> You have to use opencv and solve it. Send the data back to tiktok.

this library still working?

**Comment by mrklintscher** [comment]
No there need to make some fixes.

**Comment by deynstrausser** [comment]
Telegram @deynstrausser

**Comment by szdc** [comment]
Closing as this project is no longer maintained.
