### ISSUE TITLE
Get all followers 

### ISSUE THREAD

**Issue by tiberiu1995** [szdc/tiktok-api#149]
Hello, I want to get all the followers of an user. I managed to get 5000 followers but, after, the max_time and min_time from the response were -1. From what I understand, tiktok won't let me get more followers, even though they exist.
Does anyone know if there is a way to get all followers of an user?
Thank you!

**Comment by tamunoemi** [comment]
Hello please does this api works ?

**Comment by kshport** [comment]
There is no way to get more than 5000 subscribers, this is the tiktok limit

**Comment by szdc** [comment]
Closing as this project is no longer maintained.
