### ISSUE TITLE
login problem

### ISSUE THREAD

**Issue by fanatov37** [szdc/tiktok-api#152]
![image](https://user-images.githubusercontent.com/18050298/77258519-c2075f00-6c83-11ea-94e4-a874bc281534.png)

So I'm trying login but get  always this error

{data: Object {captcha: "", description: "You are visiting our service too frequently.", error_code: 7},

So interesting if my devide_id username, pass etc will be normal I will get same error.

Maybe someone knows how to resolve this problem !?

**Comment by intfloatbool** [comment]
+ 1

**Comment by lxstify** [comment]
Same problem. Any solutions?

**Comment by intfloatbool** [comment]
> Same problem. Any solutions?

There is no solutions. TikTok changed login logic many times since this api was updated.

**Comment by lxstify** [comment]
But how to get information about the video?

**Comment by fanatov37** [comment]
> > Same problem. Any solutions?
> 
> There is no solutions. TikTok changed login logic many times since this api was updated.

Interesting . And now login is not working :(
