### ISSUE TITLE
Live chat comments api

### ISSUE THREAD

**Issue by michaelpayne02** [szdc/tiktok-api#153]
**Is your feature request related to a problem? Please describe.**
I have seen a service called Loola that allows you to read comments sent to your live broadcast from a web interface. I wish this were possible through this api.

**Describe the solution you'd like**
A webhook, ajax url, or function that can be used as a callback for when new comments are put on a live broadcast

**Comment by CristianHG2** [comment]
Currently developing a project that urgently needs this. I've been trying to look for ways of implementing this and these are some of my small findings:

- The most efficient way of retrieving the chat feed will most likely be via TikTok's live web interface, where it's easiest to debug and profile requests and function calls.

- The feed itself works through a very basic fetch loop powered by a `setTimeout`, I didn't see any type of progressive download or websocket connection to actually retrieve messages:
![image](https://user-images.githubusercontent.com/4695165/130345268-edaff4fa-c984-4d37-9a52-e4c035ba89c5.png)

- Message payloads seem to come mixed in with actual stream data as well, and I can't seem to figure out the type of encoding the response body has.
![image](https://user-images.githubusercontent.com/4695165/130345287-a9de4584-d619-4b6a-8949-83531987df2a.png)

My level of reverse engineering experience is relatively surface-level when it comes to systems like this, but maybe we can begin a discussion here and contribute our findings. I've even thought of using software like Pupeeter to programmatically read and post to the chat using a Chromium instance, the problem there becomes the captcha that takes place during login.

**Comment by szdc** [comment]
Closing as this project is no longer maintained.
