### ISSUE TITLE
Unable to get it working with the proxy params

### ISSUE THREAD

**Issue by NeelDroid** [szdc/tiktok-api#154]
I have no idea how to get them. I tried out charles/mitm/fiddler. I am not being able to find the section where I can find these things! Currently using fiddler. If someone know how to get those details, do tell. I just started using Node since I need this API to work. I called without setting those params & got this :
`{"data":{"captcha":"","description":"For the security of the account, please upgrade to the latest  version for this operation","error_code":1049},"message":"error"}`

**Comment by Zachary24** [comment]
did you ever figure it out?

**Comment by Zachary24** [comment]
> I have no idea how to get them. I tried out charles/mitm/fiddler. I am not being able to find the section where I can find these things! Currently using fiddler. If someone know how to get those details, do tell. I just started using Node since I need this API to work. I called without setting those params & got this :
> `{"data":{"captcha":"","description":"For the security of the account, please upgrade to the latest version for this operation","error_code":1049},"message":"error"}`

did you ever figure it out?
