### ISSUE TITLE
Is this API still working?

### ISSUE THREAD

**Issue by andrearama** [szdc/tiktok-api#155]
Hi,
since it has been a while since there was an update, I was wondering if this API still works.
In fact, as far as I see there is not a TikTok version online (anymore at least) so I wonder how it is possible to fetch the data.

Thanks a lot

**Comment by michaelgnz** [comment]
Until recently it did. I was wondering if this API was going to be updated. I noticed over the last week some of the resources (namely, the ForYou feed) have switch over to using protobuf instead of JSON. I assume the rest of the resources will eventually be migrated as well, making this API useless.

**Comment by KlliksMarketing** [comment]
You can contact me at paypvt@gmail.com if you looking for a service

**Comment by PierreAndreis** [comment]
This package was built based on reverse-engineering the android app. You can check [this article ](https://medium.com/@szdc/reverse-engineering-the-musical-ly-api-662331008eb3)that explains how.

Have you tested it? Why do you think it doesn't work? An update shouldn't break dramatically this package

**Comment by mrklintscher** [comment]
Yes it still works :-)

**Comment by TylerIlunga** [comment]
@mrklintscher can I get into contact with you? I tried to use this API multiple times and had no luck...at this point the I'm concluding this is a deprecated project...

**Comment by mrklintscher** [comment]
Yes sure write me.
me@mrklintscher.de 
-------- Ursprüngliche Nachricht --------Von: Tyler Ilunga <notifications@github.com> Datum: 18.09.20  03:32  (GMT+01:00) An: szdc/tiktok-api <tiktok-api@noreply.github.com> Cc: Torsten Klinger <torsten.klinger@googlemail.com>, Mention <mention@noreply.github.com> Betreff: Re: [szdc/tiktok-api] Is this API still working? (#155) 
@mrklintscher can I get into contact with you? I tried to use this API multiple times and had no luck...at this point the I'm concluding this is a deprecated project...

**Comment by shyraqshy** [comment]
> @mrklintscher can I get into contact with you? I tried to use this API multiple times and had no luck...at this point the I'm concluding this is a deprecated project...

How can I contact with you?

**Comment by mrklintscher** [comment]
Skype: mrklintscher

shyraqshy <notifications@github.com> schrieb am So., 1. Nov. 2020, 04:57:

**Comment by doganoruc** [comment]
Hello, is there anyone who uses this API and wants to help? I couldn't figure out how to use it.

**Comment by doganoruc** [comment]
May I contact with you? @libfintx

**Comment by szdc** [comment]
Closing as this project is no longer maintained.
