### ISSUE TITLE
Add a feature to get sounds listed under "Favorites" 

### ISSUE THREAD

**Issue by ellali824** [szdc/tiktok-api#158]
On the current version of tik tok, each user has a collection of "favorites". In particular, I'm interested in getting a list of all the sounds that a user has favorited. I was wondering how to add this feature?

**Comment by masonlee277** [comment]
is this API still working?

**Comment by sourabhbagrecha** [comment]
@masonlee277 I don't think so, most of the features aren't working for me

**Comment by KlliksMarketing** [comment]
You can contact me at paypvt@gmail.com if you looking for a service

**Comment by szdc** [comment]
Closing as this project is no longer maintained.
