### ISSUE TITLE
How can I get post information? 

### ISSUE THREAD

**Issue by frostysword** [szdc/tiktok-api#164]
I see you have been able to get posts using this: https://github.com/szdc/tiktok-api#getpostid

I'm trying to decipher how you do this, but I can't seem to figure it out. 

I'll paste my code below. I've also tried putting aweme_id directly in the options instead of under params but it didn't work. How are you making this request? 

```
function getTikTokStats() {
  try {
    var url = "https://api2.musical.ly/aweme/v1/aweme/detail/";
    var options = {   
      "followRedirects" : true,
      "muteHttpExceptions": true,
      "params": {
        "aweme_id": "6829058293818821893"
      }
    };
    var result = UrlFetchApp.fetch(url, options).getContentText();
    var json = JSON.parse(result);
  } catch(e) {
    Logger.log( e);
    return "ERROR";
  }
}
```

**Comment by szdc** [comment]
Closing as this project is no longer maintained.
