### ISSUE TITLE
Implement to an Android/Flutter app

### ISSUE THREAD

**Issue by thecherrie** [szdc/tiktok-api#165]
**Is your feature request related to a problem? Please describe.**

Hi I was wondering how I could implement this into an Android or Flutter app where I could e.g. type in a username and get the userdata via this api, things such as amount of followers, following, and the profile picture. Thanks. 

**Describe the solution you'd like**

**Additional context**
Add any other context here.

**Comment by thecherrie** [comment]
> The best solution for you would be using an api. You can setup an api and run it on a server then from flutter make a get request to your server.

Okay, I'm quite new to this process, could you state some steps as to doing this? Places to research? Tools to use?

**Comment by davidteather** [comment]
You could either make your own api or use an existing one. I’ve got one you can use as a service  here https://rapidapi.com/rapidapideveloper/api/tiktok2 there’s also quite a few others on the rapidapi platform. 

Or you can develop your own restful api. I used flask for python, but you could use something like node.js and express for this library as it’s written in js. 

You would host this script on a server somewhere like on an AWS server or similar and then from flutter you can make requests to it to get tiktok data.

**Comment by baughmann** [comment]
@davidteather @thecherrie Wouldn't proxying requests to TikTok through your own server result in rate limiting/blacklisting by TikTok, depending on how many users your service has?

**Comment by davidteather** [comment]
It would limit it, but there's options to pass in other proxies when you call methods.

**Comment by eduadoospy** [comment]
i dont recieve nothing one of accounts i wait the time in description but
dont match the other one too so

Em seg., 22 de jun. de 2020 às 18:35, David Teather <
notifications@github.com> escreveu:

**Comment by eduadoospy** [comment]
the accs dont match and i dont try a lot
to log in

Em seg., 22 de jun. de 2020 às 18:41, EDUARDO VIEIRA <eduardoospy@gmail.com>
escreveu:

**Comment by baughmann** [comment]
@davidteather That's a good point idk why I didn't think of that.

@eduadoospy To be honest I'm having the same issue as you are. I would assume that it's the default error message from TikTok whenever some of the anti-spam parameters aren't created properly.

This library looks fantastic, but I just cannot seem to implement the required parameters correctly. I've tried a mix of methods found in different projects, such as those below, but cannot seem to get it:
- [tiktok-signature](https://github.com/carcabot/tiktok-signature/blob/master/index.js)
- Another project that I cannot find right now that involved getting the MD5 of the current epoch milliseconds, among other things

I'm really stumbling on implementing them. I just don't know enough about the security methods used to try to create a workaround.

**Comment by eduadoospy** [comment]
Talking in telegram call me there? Eduardoospy

Em seg, 22 de jun de 2020 18:59, Nick B <notifications@github.com> escreveu:

**Comment by baughmann** [comment]
@eduadoospy If you're talking to me, I'm not a huge Telegram guy. However, if you send me an email I can invite you to a Slack channel.

**Comment by eduadoospy** [comment]
eduardoospy@gmail.com this email

Em seg, 22 de jun de 2020 19:16, Nick B <notifications@github.com> escreveu:

**Comment by eduadoospy** [comment]
Só im in old mobile and now

Em seg, 22 de jun de 2020 19:23, EDUARDO VIEIRA <eduardoospy@gmail.com>
escreveu:

**Comment by nicholascioli** [comment]
I've implemented some of the features [here](https://github.com/nicholascioli/clack/) in flutter. Open to pull requests.

**Comment by szdc** [comment]
Closing as this project is no longer maintained.
