### ISSUE TITLE
Signing service

### ISSUE THREAD

**Issue by mrklintscher** [szdc/tiktok-api#167]
Hi,

is there a solution for an open source or paid sources implementation of the signing service for anti spam?

I will pay.

Telegram: https://t.me/mrklintscher

**Comment by shipsource** [comment]
Whoever reads it: don't be silly and provide source code unless you want TikTok to add more security measures and fuck up your sleep for the next few weeks/months. 
This code shouldn't be shared or it will end up just like IG did.

**Comment by eduadoospy** [comment]
srry bro i cant open it


Em seg., 22 de jun. de 2020 às 08:07, justshipit <notifications@github.com>
escreveu:

**Comment by baughmann** [comment]
@shipsource Could we talk offline about this? I don't necessarily want an outright answer, but I would very much like to learn more about what exactly the anti-spam parameters are and what purpose they serve.

**Comment by shipsource** [comment]
> srry bro i cant open it

You need to click "Unsubscribe" link and that should be it.

> @shipsource Could we talk offline about this? I don't necessarily want an outright answer, but I would very much like to learn more about what exactly the anti-spam parameters are and what purpose they serve.

I think the purpose is obvious: to prevent people from tampering with it. TikTok engineers ain't stupid.

**Comment by baughmann** [comment]
@shipsource Golly, thanks, mister.

**Comment by baughmann** [comment]
Well for anyone who wants some *useful* information to point you in the right direction, the answer probably lies in REing TikTik's web app. It's much harder to bury secrets in a compiled C library on the client side of a JS app.

TikTok puts 250kb of data in browser storage before even signing in, including interesting looking stuff like:
```
ssid: "e2f6a3bd-295a-4a2d-82a5-ced54d7ec986"
timestamp: 1592923816880
user_unique_id: "6841555685147756037"
web_id: "6841555685147756037"
```

**Comment by react-rxjs** [comment]
If you pay, I'll give you some very useful help
https://github.com/react-rxjs/tiktok-xlog-service

**Comment by baughmann** [comment]
@react-rxjs Why do you have that username when you have nothing to do with RxJS

**Comment by llacb47** [comment]
@baughmann what exactly are you looking for?

**Comment by baughmann** [comment]
@llacb47 Just a generic explanation of what the specific values are and what they're used for (i.e. "X is calculated based on datetime and user agent and is combined with Y to compute Z"), or really anything that can help me in figuring it out.

**Comment by mrklintscher** [comment]
Self done here https://github.com/mrklintscher/TikTokPrivateAPI
