### ISSUE TITLE
How to sign in with phone number and password?

### ISSUE THREAD

**Issue by richardARPANET** [szdc/tiktok-api#168]
I see the client has methods:

```
.loginWithEmail(email, password)
.loginWithUsername(username, password)
```

However, the tiktok app doesn't allow sign up with username OR email. Only phone number or social login.

Given I have a phone number and password for login, how do I login with this using this client?

Thanks!

edit: Alternatively, do you know of a way of signup up via username or email at this time?

**Comment by mrklintscher** [comment]
@richardARPANET look here https://github.com/mrklintscher/TikTokPrivateAPI

**Comment by kshport** [comment]
Registration via mail now works in the tiktok application, I'm talking about version 17

If you have a password for your account, just enter your username in tiktok and your password when logging in.

**Comment by hugit6** [comment]
just wondering if this project works today? (2020.10)

**Comment by mrklintscher** [comment]
This dosent Work anymore.

hugit6 <notifications@github.com> schrieb am Di., 13. Okt. 2020, 05:27:

**Comment by hugit6** [comment]
so there is no working prject use code api to behavior tiktok?
I see some project use chrome for web tiktok, that not what i want.


On 10/13/2020 13:15, Torsten Klinger wrote:

This dosent Work anymore.

hugit6 <notifications@github.com> schrieb am Di., 13. Okt. 2020, 05:27:
