### ISSUE TITLE
Is this API still usable in 2020?

### ISSUE THREAD

**Issue by PeterGardas** [szdc/tiktok-api#169]
The title says it all. I am just curious. Also is it only able to run on a mobile phone or can i run it on PC?

**Comment by PeterGardas** [comment]
Just saw that this question was already answered. Sorry for opening another one.

**Comment by eduadoospy** [comment]
Bro it dont works

Em seg, 22 de jun de 2020 08:09, Peter Gardas <notifications@github.com>
escreveu:
