### ISSUE TITLE
Ads

### ISSUE THREAD

**Issue by SSRTC** [szdc/tiktok-api#175]
Is it possible to view ads using your framework, as it is done in the Tiktok mobile app

**Comment by hugit6** [comment]
I am also interesting in this. Would you like to chat with me for this?

**Comment by PotaninMarat** [comment]
Hi

**Comment by PotaninMarat** [comment]
What do you mean?

**Comment by hugit6** [comment]
i am working on view ads in tiktok too


On 10/13/2020 12:20, Marat wrote:

What do you mean?

**Comment by PotaninMarat** [comment]
I am a .net (C #) developer and I am thinking of porting your solution to C # .net standard. What do you think about this?

**Comment by hugit6** [comment]
> I am a .net (C #) developer and I am thinking of porting your solution to C # .net standard. What do you think about this?

Why you need AD infor?

**Comment by PotaninMarat** [comment]
"i am working on view ads in tiktok too"
at what stage of development?

**Comment by hugit6** [comment]
> "i am working on view ads in tiktok too"
> at what stage of development?

just start stage

**Comment by szdc** [comment]
Closing as this project is no longer maintained.
