### ISSUE TITLE
axios_cookiejar_support_1.default should be axios_cookiejar_support_1

### ISSUE THREAD

**Issue by kgaspard** [szdc/tiktok-api#182]
Thanks for the package, excited to start using it!
Unfortunately `axios_cookiejar_support_1.default(this.request)` doesn't seem to be working. I was able to get it to work by replacing by `axios_cookiejar_support_1(this.request)`

I'm not an axios expert, but would fixing this in the source still keep things working?

**Comment by kgaspard** [comment]
For context: it seems to be working server side (although with a "'You are visiting our service too frequently.'" error) but I'm encountering this error when importing the package client side with webpack

**Comment by szdc** [comment]
Closing as this project is no longer maintained.
