### ISSUE TITLE
Delete a comment, filter comment by keywords

### ISSUE THREAD

**Issue by balahmadi-Ox** [szdc/tiktok-api#183]
**Is your feature request related to a problem? Please describe.**
Through a script or another mobile app, I would like to be able to interact automatically with my TikTok account to analyse comments and delete abusive comments.

**Describe the solution you'd like**
Extend the API to be able to interact with a users account to delete a comment by id, or update the keywords in the "filter comments" feature provided by TikTok automatically.

**Additional context**
Can this feature be added to this API? Are there any other APIs available that provide this functionality? Is this even possible?

**Comment by szdc** [comment]
Closing as this project is no longer maintained.
