### ISSUE TITLE
all parameters needed to start

### ISSUE THREAD

**Issue by Arsi44** [szdc/tiktok-api#190]
Hi guys,

Can you tell me all parameters what i need to generate by myself to start working with this api,
and where can i get it, please?

**Comment by ar-naseef** [comment]
Did you figure out this?

**Comment by deynstrausser** [comment]
If you need information about the security params, contact me. deynstrausser@protonmail.com

**Comment by MiloAkerman** [comment]
I'm also interested. I don't understand what to set for the start-up parameters, and a comment explaining them (or giving an example) would be much appreciated.

**Comment by ziadab** [comment]
I'm also interested

**Comment by doganoruc** [comment]
Hi, is there anyone who finds a solution for these params?

**Comment by tiktokxgorgon** [comment]
@doganoruc @ziadab @MiloAkerman @ar-naseef @Arsi44 

you can telegram me at: https://t.me/adotdaniel or email xgorgon@protonmail.com

**Comment by szdc** [comment]
Closing as this project is no longer maintained.
