### ISSUE TITLE
Uncaught TypeError: axios_cookiejar_support_1.default is not a function at new TikTokAPI

### ISSUE THREAD

**Issue by vkudymov** [szdc/tiktok-api#192]
At startup
const signURL = async (url, ts, deviceId) => {
       const as = 'anti-spam parameter 1';
       const cp = 'anti-spam parameter 2'
       const mas = 'anti-spam parameter 3';
       return `$ {url} & as = $ {as} & cp = $ {cp} & mas = $ {mas}`;
     }
     const params = getRequestParams ({
       device_id: '<device_id>',
       fp: '<device_fingerprint>',
       iid: '<install_id>',
       openudid: '<device_open_udid>',
     });
    
     const api = new TikTokAPI (params, {signURL});

An error
Uncaught TypeError: axios_cookiejar_support_1.default is not a function at new TikTokAPI

How can you win?

**Additional context**

**Comment by szdc** [comment]
Closing as this project is no longer maintained.
