### ISSUE TITLE
A working API

### ISSUE THREAD

**Issue by dexy-hot** [szdc/tiktok-api#194]
Hi,
I've been trying to work around this api but it seems its missing a lot of security stuff and cant get it to work properly.
TikTok really trying too hard to prevent reverse engineering.
Anyone knows any other unofficial APIs? All i was able to find was https://tikapi.io/ but it doesnt seem to have any free plans and its not open source.

Let's hear some more opinions on this,
Thanks

**Comment by demon071** [comment]
> Hi,
> I've been trying to work around this api but it seems its missing a lot of security stuff and cant get it to work properly.
> TikTok really trying too hard to prevent reverse engineering.
> Anyone knows any other unofficial APIs? All i was able to find was https://tikapi.io/ but it doesnt seem to have any free plans and its not open source.
> 
> Let's hear some more opinions on this,
> Thanks

Currently tiktok has blocked access to api user info but the other api still works normally, can get video_id

**Comment by Venack** [comment]
If you are looking for a mobile version of the API, more stable and reliable check out this [repository](https://github.com/Venack/tiktokapi) (unfortunately this is not a free version)

**Comment by szdc** [comment]
Closing as this project is no longer maintained.
