### ISSUE TITLE
Getting Devices parameters

### ISSUE THREAD

**Issue by TomAvecLeVdsl** [szdc/tiktok-api#204]
Hi guys, apparently in a new tiktok update they blocked api access whenever a proxy is detected probably to prevent the use of tool like this one

but anyway have anyone beein able to bypass that ?
Thanks for the help

**Comment by TomAvecLeVdsl** [comment]
Link to #147 As it's the exact same problem

**Comment by szdc** [comment]
Closing as this project is no longer maintained.
