### ISSUE TITLE
Help for ant-spam parameter

### ISSUE THREAD

**Issue by higordiasz** [szdc/tiktok-api#205]
Now to i get the parameter ? ... parameter of device i get with HTTP Toolkit .. how to i get the parameter ? .. anyone help-me ? 

My discord: Dias#1869

**Comment by marcelogrsp** [comment]
I am also trying to find out it, awful documentation on readme.md

**Comment by dvird** [comment]
https://github.com/iio97/i-frida-server/blob/6e65bcc3bbceeb0bdee96580a250fb1b6b0ccb29/tiktok/rpc.js

**Comment by higordiasz** [comment]
@dvird Thanks bro .. but i was unable to implement .. is possible you help me ? .. if yes .. call me on Telegram @higordiasz or Discord Dias#1869

**Comment by aimadnet** [comment]
Frida won't work for you, TikTok can detect it.

**Comment by xgorgon** [comment]
Can sell you. Mail. Me at xgorgon@protonmail.com

**Comment by tiktokxgorgon** [comment]
you can telegram me at: https://t.me/adotdaniel

**Comment by szdc** [comment]
Closing as this project is no longer maintained.
