### ISSUE TITLE
Get videos by Topic

### ISSUE THREAD

**Issue by kicks66** [szdc/tiktok-api#219]
TikTok recently updated with a new section of their app called "Topics":

![IMG_8083](https://user-images.githubusercontent.com/4125092/122530400-5642ac00-d016-11eb-9d2c-fefc924ff79f.PNG)

Clicking on a Topic opens up a new infinite-scrolling stream of videos within that particular Topic. These videos do not have hashtags or particular descriptors that define them as being part of a Topic.

I'd like to know if its possible to find the routes which create this list of videos, and if its possible to integrate this into the API?

**Comment by szdc** [comment]
Intercept the traffic with an app like `mitmproxy`.

This project is no longer maintained so I can't help you more.
