### ISSUE TITLE
Device parameters.

### ISSUE THREAD

**Issue by Hoodgail** [szdc/tiktok-api#220]
**Describe the bug**
Unable to get the required device parameters

**To Reproduce**
```js
/**
 * Required - device parameters
 * You need to source these using a man-in-the-middle proxy such as mitmproxy,
 * CharlesProxy or PacketCapture (Android)
 */
const params = getRequestParams({
     device_id: '',
     fp: '<device_fingerprint>',
     iid: '<install_id>',
     openudid: '<device_open_udid>',
});
```

**Additional context**
How can i get the device id's for usage

**Comment by aimadnet** [comment]
You need frida to bypass ssl and mitmproxy

**Comment by jakecrowley** [comment]
> You need frida to bypass ssl and mitmproxy

Can you share a method to bypass SSL using frida? I have both rooted android and jailbroken ios and have been trying to use objection's sslpinning bypass with no luck after installing my own root CA's.

**Comment by aimadnet** [comment]
drop me a message on telegram: aimadnet

**Comment by tiktokxgorgon** [comment]
you can telegram me at: https://t.me/adotdaniel

**Comment by szdc** [comment]
As specified in the code snippet you pasted: `You need to source these using a man-in-the-middle proxy such as mitmproxy.`

However, this project is no longer maintained so I can't help you more.
