### ISSUE TITLE
Tiktok Go Live Button Hidden

### ISSUE THREAD

**Issue by Tom13666** [szdc/tiktok-api#223]
**Describe the bug**
Tiktok Go Live Button Hidden.

**To Reproduce**
I don't what the code is.

**Expected behavior**
On the TikTok website, I don't have the "Go Live" button.
And on the TikTok app, after clicking "Live", I don't have the "Cast on PC/Mac" button.

**Additional context**
I met all the requirements of the live broadcast, and I can broadcast live on my mobile phone, but the go live button of Tik Tok on the web page does not appear. I know someone can crack it, but he doesn't tell anyone, so I am here to ask for help.

**Comment by lingdusi** [comment]
Great God, is there a solution

**Comment by szdc** [comment]
Closing as this is beyond the scope of this project.
