### ISSUE TITLE
List "For You" page?

### ISSUE THREAD

**Issue by laranjaquadrada** [szdc/tiktok-api#25]
Hi,

Is it possible to get a list of "For You" videos similar to what we get in the .listPosts ?

I am assuming that .listPosts only lists videos of the current user_id. Would be good to list all videos for all users, as they appear in the "For You" page screen.

For example:
 .listForYouPosts(params)
Lists posts for the user's For You page.

api.listForYouPosts({
  user_id: '<user_id>',
  max_cursor: 0,
})
  .then(res => console.log(res.data.aweme_list))
  .catch(console.log);

// Outputs:
// [{ author: {...}, aweme_id: '999', desc: 'description', music: {...}, statistics: {...}, video: {...} },

**Comment by szdc** [comment]
Yep, I'll get this done.
