### ISSUE TITLE
Tiktok Live

### ISSUE THREAD

**Issue by finicky** [szdc/tiktok-api#26]
Do you have any plans to add endpoints for live streams on Tiktok?

**Comment by szdc** [comment]
Yeah this can be done.

**Comment by szdc** [comment]
Thanks for raising this issue - the response from the [`joinLiveStream()`](https://github.com/szdc/tiktok-api#joinlivestreamid) call contains the URL of the actual stream.

**Comment by Mindinfoservices** [comment]
Could i get RMTP url from api tiktok . Please reply
