### ISSUE TITLE
Add functionality to save and load cookies

### ISSUE THREAD

**Issue by szdc** [szdc/tiktok-api#30]
At the moment you have to login every time you start a new instance of the API.  Sessions last longer than that, so we should have the ability to load and use an existing session.

**Comment by toklok** [comment]
question:  what would be good reading material for this?

**Comment by szdc** [comment]
@toklok we're using tough cookie so and they have support for [serializing and deserializing the cookie jar](https://github.com/salesforce/tough-cookie#serializecberrserializedobject) so saving and loading that from a file would be good.

**Comment by szdc** [comment]
I am happy to address handling expired/invalid sessions in a separate issue.

**Comment by szdc** [comment]
Closing as this project is no longer maintained.
