### ISSUE TITLE
Error while importing getRequestParams

### ISSUE THREAD

**Issue by shashank0708** [szdc/tiktok-api#35]
I am running the app like this:-
`node --experimental-modules index.mjs`

and this is line is giving error  
`import TikTokAPI, { getRequestParams } from 'tiktok-api';`

error:- 
```
(node:5872) ExperimentalWarning: The ESM module loader is experimental.
TypeError: getRequestParams is not a function
    at file:///D:/Node.js/FirstTry/index.mjs:14:16
    at ModuleJob.run (internal/loader/ModuleJob.js:97:14)
    at <anonymous>
```
 P.S I am new to node.js.

**Comment by lijuanliu2018** [comment]
Hi, @shashank0708 

How dow you fix this? We meet the same issue.

**Comment by szdc** [comment]
@lijuanliu2018 ECMAScript Modules are [still experimental](https://nodejs.org/api/esm.html#esm_ecmascript_modules) so I'm not inclined to invest into resolving this.  Use Babel, TypeScript, etc. if you want this functionality now.

Alternatively, you are able to work around this by simply using the default export:
```js
import TikTokAPI from 'tiktok-api';

const requestParams = TikTokAPI.getRequestParams({...});
```
