### ISSUE TITLE
Where to start?

### ISSUE THREAD

**Issue by Zachary24** [szdc/tiktok-api#41]
What would be needed to download all videos from someones (my) profile? I have over 1,000 and don't feel like downloading each one.. I've been learning python, but the documentation here is fuzzy. Any help is appreciated!

**Comment by Zachary24** [comment]
Sorry, I'm still a little confused... Would i use python? Is the user_id the username or an actual id? And some things im a little confused about are below.. 

  const as = 'anti-spam parameter 1';
  const cp = 'anti-spam parameter 2'
  const mas = 'anti-spam parameter 3';

  device_id: '<device_id>',
  fp: '<device_fingerprint>',
  iid: '<install_id>',
  openudid: '<device_open_udid>',


Is there any "working" example? thanks!

**Comment by szdc** [comment]
Each user is assigned a unique numeric identifier, which is their `user_id`.  It cannot be changed and is separate from the user's username (which can be changed).  The easiest way to get a user's id is to [search for the user](https://github.com/szdc/tiktok-api#searchusersparams) - the response data contains a list of users, and each user has a `uid` field containing their user id.

I don't provide a working example for generating the anti-spam parameters in this library because that would defeat their purpose.  I would take a look at the discussion in #9 for some hints about how you could generate them yourself.

`device_id`, `fp`, `iid` and `openudid` are all identifiers relating to your device, which you could get by intercepting traffic on your Android phone using [mitmproxy](https://mitmproxy.org/) or similar.

**Comment by ValkA** [comment]
decompiled appendAntiSpamParams() in case somebody wants it:

`  public static n appendAntiSpamParams(n paramn, List<String> paramList, int paramInt)
  {
    String str2 = URLDecoder.decode(paramn.toString());
    Object localObject2 = DeviceRegisterManager.getDeviceId();
    Object localObject1;
    if ((str2.contains("&device_id=")) || (str2.contains("?device_id=")))
    {
      localObject1 = localObject2;
      if (TextUtils.isEmpty((CharSequence)localObject2)) {
        localObject1 = (String)URLRequest(str2).get("device_id");
      }
      String str1 = UserInfo.getUserInfo(paramInt, (String[])paramList.toArray(new String[paramList.size()]), null, (String)localObject1);
      localObject2 = localObject1;
      localObject1 = str1;
      paramn = paramn.newBuilder();
      int i = ((String)localObject1).length();
      if (TextUtils.isEmpty((CharSequence)localObject1)) {
        break label273;
      }
      if (i % 2 != 0) {
        break label242;
      }
      paramList = ((String)localObject1).substring(0, i >> 1);
      localObject1 = ((String)localObject1).substring(i >> 1, i);
      localObject2 = a.getSDK(GlobalContext.getContext(), AwemeApplication.getInst().getAid());
      ((ISdk)localObject2).setSession(m.getSessionId());
      localObject2 = EagleEye.byteArrayToHexStr(((ISdk)localObject2).encode(paramList.getBytes()));
      paramn.addQueryParameter("as", paramList).addQueryParameter("cp", (String)localObject1).addQueryParameter("mas", (String)localObject2);
    }
    for (;;)
    {
      return paramn.build();
      localObject1 = UserInfo.getUserInfo(paramInt, (String[])paramList.toArray(new String[paramList.size()]), null, "");
      break;
      label242:
      d.monitor(str2, paramList, (String)localObject1, (String)localObject2, paramInt);
      paramn.addQueryParameter("as", "a1qwert123").addQueryParameter("cp", "cbfhckdckkde1");
      continue;
      label273:
      d.monitor(str2, paramList, (String)localObject1, (String)localObject2, paramInt);
      paramn.addQueryParameter("as", "a1iosdfgh").addQueryParameter("cp", "androide1");
    }
  }`

**Comment by ioio101** [comment]
> Each user is assigned a unique numeric identifier, which is their `user_id`. It cannot be changed and is separate from the user's username (which can be changed). The easiest way to get a user's id is to [search for the user](https://github.com/szdc/tiktok-api#searchusersparams) - the response data contains a list of users, and each user has a `uid` field containing their user id.
> 
> I don't provide a working example for generating the anti-spam parameters in this library because that would defeat their purpose. I would take a look at the discussion in #9 for some hints about how you could generate them yourself.
> 
> `device_id`, `fp`, `iid` and `openudid` are all identifiers relating to your device, which you could get by intercepting traffic on your Android phone using [mitmproxy](https://mitmproxy.org/) or similar.

What about the timestamps?

**Comment by szdc** [comment]
@ioio101 you generate the timestamp yourself - it is simply the current time when you are making the call.

**Comment by ioio101** [comment]
> @ioio101 you generate the timestamp yourself - it is simply the current time when you are making the call.

Are the rest of the device identifiers static? Anything else besides timestamp/anti spam parameters that needs dynamic generation?

**Comment by szdc** [comment]
@ioio101 that's right - the other parameters are static. Note that [`_rticket`](https://github.com/szdc/tiktok-api/blob/master/src/index.ts#L526) is another timestamp (the current time in milliseconds).

**Comment by favourodoyo** [comment]
By the way,  which programming language or platforms CAn I write Tiktok api on?.. Is it ionic or react?

**Comment by favourodoyo** [comment]
They just placed it there with out showing which platform to run it on.. I know it javascript Es6..but how do you call the api on ionic or react?
