### ISSUE TITLE
anti-spam parameters

### ISSUE THREAD

**Issue by LucioCarrera** [szdc/tiktok-api#42]
Can you expand more on this topic? Can you give some kind of example or explain what you want to say with "a method that signs the URL with anti-spam parameters".
Thanks

**Comment by szdc** [comment]
Requests made by the TikTok app are signed with 3 anti-spam parameters: `as`, `cp` and `mas`.  The signing process is non-trivial and uses a shared C++ library.

The easiest approach would be to look at how the Android app uses the [Java Native Interface](https://www.baeldung.com/jni) to bridge between Java and the shared library, and think about how you might implement something on a smaller scale.

I'm closing this issue as it is too similar to #9.

**Comment by LucioCarrera** [comment]
Thanks I just found how the app creates those parameters.

**Comment by sskhokhar** [comment]
@NoNameSorryButHeyCallMeSherlock  Can you please provide me with the process? Your help will highly be appreciated.

**Comment by NoNameSorryButHeyCallMeSherlock** [comment]
@sskhokhar I don't want to link the repository directly but look into my profile and looks for the anti-spam repository.

**Comment by cook1e-monster** [comment]
@LCSP can you add here the anti-spam repository ?  thanks

**Comment by maximilianschmelzer** [comment]
@cook1e-monster https://github.com/LCSP/tiktokapi-security
