### ISSUE TITLE
Streaming from OBS

### ISSUE THREAD

**Issue by humet** [szdc/tiktok-api#45]
Hi,

I was wondering if it was possible to supply this API an RTMP stream URL to start a live broadcast? Or if it's a feature you would look to adding? 

This Instagram API does it in a similar manner to this one: https://github.com/mgp25/Instagram-API/blob/master/src/Request/Live.php 

Thanks

**Comment by szdc** [comment]
Should be possible, though I don't have an account with 1,000 followers (the minimum required to broadcast) so this would be a little harder to test.

**Comment by humet** [comment]
Great thanks. I can get account details over to you. What would I need to do to get this done?

**Comment by szdc** [comment]
@humet send me a PM on [Twitter](https://twitter.com/dotszdc) and I'll take a look.

**Comment by aymehai** [comment]
Do you think you could also help me get the RTMP stream URL and also get the streamid (stream key)?

**Comment by szdc** [comment]
@aymehai this issue was closed in 2018 please open a new issue if you have questions
