### ISSUE TITLE
How to get parameter for function UserInfo.initUser?

### ISSUE THREAD

**Issue by dixakman** [szdc/tiktok-api#59]
Hello friends!

How to get parameter for function UserInfo.initUser? 
I can not find either ...

**Comment by szdc** [comment]
Look at the calls made to that function in the apk and you'll see it's defined as a constant.

**Comment by dixakman** [comment]
> Look at the calls made to that function in the apk and you'll see it's defined as a constant.

I saw the constant, but there is also a function to get the value from the cache. To initialize the constant enough. The value itself is taken into account when forming signatures?

**Comment by szdc** [comment]
Last I checked the cached value didn't change, so you'll be right using the constant.

**Comment by dixakman** [comment]
> Last I checked the cached value didn't change, so you'll be right using the constant.

Thx, setAppId 4 digit number? Or some long number?

**Comment by szdc** [comment]
`1233` is the app ID for TikTok, same as defined [here](https://github.com/szdc/tiktok-api/blob/master/src/index.ts#L573).
