### ISSUE TITLE
Cant use any feature

### ISSUE THREAD

**Issue by roberttrisch** [szdc/tiktok-api#65]
i am only being able to login, data of my account is fetching but whenever i try to use any other feature as listing post or something like that i always i get undefined, even tho i define it as you said.

**Comment by szdc** [comment]
Please provide an example of what you mean when you say you are getting undefined.

**Comment by roberttrisch** [comment]
is there anyway i can contact you in private, as i have to share the code that i am using and other things so you can easily see whats the problem

**Comment by szdc** [comment]
DM me on Twitter: https://twitter.com/dotszdc

**Comment by roberttrisch** [comment]
i cant send messages to you because you don't receive messages from people you don't follow
my twitter is: https://twitter.com/RobertFredj6485

**Comment by szdc** [comment]
User contacted me over Twitter and was being asked to sovle a captcha on login - I have only ever seen this come up after repeated failed login attempts, and the solution is to solve the captcha in-app and then resume your API calls.
