### ISSUE TITLE
Example of work in production use

### ISSUE THREAD

**Issue by embedfile** [szdc/tiktok-api#67]
I was able to port this code over to PHP and I made a simple platform using it. TikTok has long and ugly profile URLs. Outside of this wrapper and the actual app there really is no solid way to be able to view a TikTok profile just by knowing the username. With that in mind I put together TikTok2.me which provides users with easy to remember tiktok2.me/username profile links. Users can visit the homepage, enter their username and be provided with a URL or they can just link to tiktok2.me/username and it will function the same.

https://tiktok2.me

**Comment by szdc** [comment]
You're not a direct consumer of this API so I'm hesitant to link to you as I see your work to be more inspiration than example.  If you open-sourced your PHP library I'd be happy to link to it :smile:
