### ISSUE TITLE
Add a method to get a post by its id

### ISSUE THREAD

**Issue by iosys** [szdc/tiktok-api#68]
**Is your feature request related to a problem? Please describe.**
Currently the only way to get a post's data is to get all posts from a user until the desired post is reached.
The API has a way to get a single post if you know its id which can be useful sometimes.

**Describe the solution you'd like**
The API call is 'aweme/v1/aweme/detail/' with param aweme_id
The result contains the Post in aweme_detail

**Additional context**
There are some minor differences in the data returned by this call compared to the one used in listPosts(), but nothing important is missing. Can provide examples if needed.

**Comment by szdc** [comment]
I'm surprised that I missed this one - thanks for pointing it out, I'll get it done.

**Comment by szdc** [comment]
Thanks for the request! I've just added the [endpoint](https://github.com/szdc/tiktok-api#getpostid).  I'll create a new issue to address the missing `Post` fields as the app has been updated.
