### ISSUE TITLE
Is there a way to get all posts regardless of users?

### ISSUE THREAD

**Issue by axiom88-guru** [szdc/tiktok-api#69]
First of all, you've done an amazing job. Well done. 
I am looking at this api now: .listPosts(params)
It seems to me it is limited to get posts based on users according to your param example. 
api.listPosts({
  user_id: '<user_id>',
  max_cursor: 0,
})
  .then(res => console.log(res.data.aweme_list))
  .catch(console.log);

So my question is, can we get all posts regardless of users? 
Your answer would be appreciated.
Regards!

**Comment by szdc** [comment]
Not using that endpoint.  To achieve what you want, look at the [`ListForYouFeed`](https://github.com/szdc/tiktok-api#listforyoufeedparams) endpoint, which is an infinite list of posts (curated to your account).  You'll need to use the [`max_cursor`](https://github.com/szdc/tiktok-api/blob/master/src/types/request.d.ts#L163) field for pagination

There are also a couple of other endpoints if you want to limit your search:
* [`ListPostsInHashtag`](https://github.com/szdc/tiktok-api#listpostsinhashtagparams) to restrict posts to those within a specific hashtag
* [`ListFollowingFeed`](https://github.com/szdc/tiktok-api#listfollowingfeedparams) to restrict posts to only users that your account follows
