### ISSUE TITLE
How to Download Videos without Watermark?

### ISSUE THREAD

**Issue by 23233** [szdc/tiktok-api#73]
## How to Download Videos without Watermark?

**Comment by szdc** [comment]
Once you have information about the post (through one of many calls, e.g. [ListPosts](https://github.com/szdc/tiktok-api/blob/master/src/index.ts#L179)), the [`video`](https://github.com/szdc/tiktok-api/blob/master/src/types/post.d.ts#L69) key contains information about the video.  [`has_watermark`](https://github.com/szdc/tiktok-api/blob/master/src/types/video.d.ts#L14) will tell you if the video is watermarked, in which case the download url query string will contain  `watermark=1`.

If you remove this parameter from the url (or set it to 0), you'll be able to download the video without a watermark.

**Comment by kishan2212** [comment]
i checked the page source but they removed and changed it water mark tag inside of Video key.
 can you help me out ?

**Comment by Mateeen** [comment]
@kishan2212 did you found any solution?

**Comment by kishan2212** [comment]
> @kishan2212 did you found any solution?

not yet. did you found any solution ? they updated source...

**Comment by KanaiyaKatarmal** [comment]
I have got the solutions for downloading video without water mark.

**Comment by Mateeen** [comment]
@KanaiyaKatarmal can you please tell how?

**Comment by KanaiyaKatarmal** [comment]
@Mateeen 
Please discuss this topic in private.
katarmal.kanaiya@gmail.com

**Comment by Mateeen** [comment]
be aware of this guy named @KanaiyaKatarmal  he is not helping the community he will ask you to come in private inbox and will ask you 500$ dollars
