### ISSUE TITLE
Add methods to get posts by music and by stickers

### ISSUE THREAD

**Issue by visua0** [szdc/tiktok-api#76]
**Is your feature request related to a problem? Please describe.**
There are a couple more endpoints for which there is no method available yet.

**Describe the solution you'd like**
'/aweme/v1/music/aweme/' with param music_id
'/aweme/v1/sticker/aweme/' with param sticker_id
They both use cursor instead of max_cursor in requests and responses.

**Additional context**
Stickers are the video filters/effects.
I haven't looked at these extensively yet, so there might be other differences between listPosts and these.

**Comment by szdc** [comment]
Thanks, I'll get these done.

**Comment by szdc** [comment]
Closing as this project is no longer maintained.
