### ISSUE TITLE
Consulting

### ISSUE THREAD

**Issue by hackydunk** [szdc/tiktok-api#78]
Hey! @szdc 

Can you reach out to me on skype at hacky20091?

I'd like to pay you to help me develop a small web application using this api... I can delete this issue after you contact me. 

Thanks,
J

**Comment by klliks-com** [comment]
@szdc my username on twitter: @JLucky888

I have a legit reason, really need help. Please DM or leave me some way to communicate its urgent.

**Comment by szdc** [comment]
No thank you.
