### ISSUE TITLE
Get Followed users return empty response in .NET

### ISSUE THREAD

**Issue by romanGarasymovych** [szdc/tiktok-api#79]
Hello,

First of all, thanks for such an amazing work you have put in into this API. 

I am currently trying to implement this API on an ASP.NET server, with some success. But `aweme/v1/user/follower/list/` is giving me a headache. I receive empty response when calling it using `HttpClient` on my ASP.NET server. I use the parameters from my own device, and can get my followers on _Postman_ with no issues. Doesn't work in C#.

This is the code I use:
```
bool hasMore = true;
int maxTime = (int)DateTime.UtcNow.Subtract(new DateTime(1970, 1, 1)).TotalMilliseconds;

string request = $"https://api2.musical.ly/aweme/v1/user/follower/list/?{params}";

using (HttpClient client = new HttpClient(new HttpClientHandler() { AutomaticDecompression = DecompressionMethods.Deflate }))
            {
                var req = new HttpRequestMessage(HttpMethod.Get, request);
                var response = await HttpClient.SendAsync(req);
                using (Stream stream = await response.Content.ReadAsStreamAsync())
                using (StreamReader reader = new StreamReader(stream))
                {
                    var json = JObject.Parse(await reader.ReadToEndAsync());
                    JArray followers = json.Value<JArray>("followers");
                    foreach (JObject follower in followers)
                    {
                        string id = follower.Value<string>("uid");
                        if (id.Equals(tikTokUserId)) return true;
                    }
                    hasMore = json.Value<bool>("has_more");
                    maxTime = json.Value<int>("min_time");
                }
            }
```

I tried different ways of sending the request, but the result is always the same. I understand if you can't help, and feel free to close the issue if you consider it irrelevant to the project.

Thanks!

**Comment by Pilfer** [comment]
Connect your HttpClient to a proxy like Charles or Burp and view whats *actually* being sent to the API server. Compare that with what is sent in Postman. You'll have your answer.

**Comment by romanGarasymovych** [comment]
Thanks for your response.

User Agent was the issue. I was not setting it correctly, and it looks like `/aweme/` endpoint cares about it more than others do.
