### ISSUE TITLE
X-Tt-Token

### ISSUE THREAD

**Issue by asosyetikbiri** [szdc/tiktok-api#81]
Hello!

update X-Tt-Token ?

**Comment by szdc** [comment]
Please provide more information

**Comment by asosyetikbiri** [comment]
We get the X-Tt-Token entrance, X-Tt-Token expires, what should we do?

**Comment by mrklintscher** [comment]
@asosyetikbiri you dont need it. Use coockie instead.

**Comment by kshport** [comment]
You can use /aweme/v1/im/cloud/token/ endpoint for this

**Comment by elv1337** [comment]
> You can use /aweme/v1/im/cloud/token/ endpoint for this

how can you do that, im kind of new to this and i dont know how to use it

**Comment by szdc** [comment]
Closing as this project is no longer maintained.
