### ISSUE TITLE
"data":{"captcha":"","description":"You are visiting our service too frequently.","error_code":7},"message":"error"}

### ISSUE THREAD

**Issue by klliks-com** [szdc/tiktok-api#82]
Hi Guys!

I have reversed all the libs including register deviceID.
But when i am trying to login i get error:
"data":{"captcha":"","description":"You are visiting our service too frequently.","error_code":7},"message":"error"}

Then account marked as bad and nothing works.

1. Created account on BOTplatform, imported to device, followed user -  counter worked
2. Tried to login and follow with that user on BOTplatform - not worked.
3. Retried #1 on real device ==Counter Not working, account is bad.

We are getting good response for the like/follow actions but counter not going up since accounts is marked as bad.

What am i doing wrong? 
We are using cookies session restore for keep accounts online.

Will pay for whom can help me.

**Comment by klliks-com** [comment]
I know. i don't do ANY spam (we been talking in skype) 
I just want to find out what you doing differently when login? 

Why my accounts are bad.

**Comment by szdc** [comment]
Your question is not related to this repository and this repository is not the right forum for it.
