### ISSUE TITLE
Unable to login via api

### ISSUE THREAD

**Issue by IgorGee** [szdc/tiktok-api#83]
I'm attempting to call the `searchHashtags` api, but the data is *usually* the following response:

```javascript
{ status_code: 2483,
  status_msg: 'Please login your account first',
  log_pb: { impr_id: '<numbers>'},
  extra:
   { logid: '<numbers>',
     now: 1547262107596,
     fatal_item_ids: [] } }
```

I say usually because I've seen it work before without even logging in on the api, but then immediately failing after. Now it's just consistently failing.

I've tried  logging in via the api before calling the `searchHashtags` api, but it asks me to solve a captcha in the response. I noticed in #65 you stated that simply logging into the application on an actual device will resolve the issue. However, I've attempted this multiple times and it still produces the same result.

Also worth noting, when logging back into the application on an actual device, I'm initially asked to solve a captcha. When solving this captcha, I get an error at the login screen stating:
`Missing ID certification information.`

Btw, the method in which I am signing my URLs is by dynamically changing the keys. I do this by observing the native device api calls via MITM program and grabbing the keys from the called URLs. I'm not sure if this is an ok method.

Edit: Pressing login again after that "Missing ID" error logs me in successfully.

**Comment by szdc** [comment]
Logging in on your real device would only work if you were using _exactly_ the same parameters.  Otherwise, you were right in solving the captcha.  

I'm not sure about the `Missing ID certification information` error you're getting - it looks like a response from the server, and I haven't encountered it.

**Comment by IgorGee** [comment]
Thanks! That comment made me rethink my implementation and the issue ended up going away.
