### ISSUE TITLE
After 10 likes, the API stops working for 5-10 minutes

### ISSUE THREAD

**Issue by dixakman** [szdc/tiktok-api#85]
Made a bot on the phone application for signing requests. I try to put 20 likes from 20 different accounts, only 10 are put in the end, the rest comes with the answer is_digg = 1 (I’m not set), after 5-10 minutes if I repeat the procedure, it works again, and only 10 again. Someone you know in what's the problem?

**Comment by szdc** [comment]
You are being restricted by the server.  This repository is not the place for both support.
