### ISSUE TITLE
Dynamically creating the antispam parameters...

### ISSUE THREAD

**Issue by ph1go** [szdc/tiktok-api#9]
Any ideas on this? They seem to be renewed with every request and they also seem to be required for every API call I've tried... 

I've found a function `appendAntiSpamParams` and I've recreated the `byteArrayToHexStr` function but a) I don't see anywhere where the `ts` argument is used (and it must be because if it was just based off of the `deviceId`, the spam params would be the same every time) and b) there's some sort of encoding that happens before the hex function and I lost the will to persevere, trying to navigate their code.

**Comment by szdc** [comment]
If you're looking at the smali code, the 3rd parameter (referred to as `p2`) passed to `#appendAntiSpamParams()` is the current timestamp - have a look at where this parameter is used within the method.  As for the encoding, reverse engineering this is non-trivial so you'll have to think outside the box.

Sorry for being reasonably vague but the reason why I require the end user to supply their own signing method is because these are anti-spam measures and the intention of this library isn't to break them.

**Comment by ph1go** [comment]
Ok, I guess I see where you're coming from (although why release this project at all if you're not going to make it usable?) 

I've had the old musical.ly/live.ly API working for ages and it still works but I expect there'll come a time when they retire it. I don't do Java and I don't understand what the `getUserInfo` method is supposed to return and how it is supposed to go about returning it. Everything else in the antispam method more or less makes sense. I guess that's the non-trivial bit, huh?

**Comment by szdc** [comment]
@ph1go this library isn't for everyone - adding the signing method would make this library a magnet for people to write bots to spam with, and that's not something I support.  This project is usable if you add the signing method yourself and also serves as a starting point for someone wanting to create something similar.  If you have a legitimate use case, [DM me on Twitter](https://twitter.com/dotszdc) and I'll give you some help.

**Comment by nowm** [comment]
> @ph1go this library **isn't for everyone** - adding the signing method would make this library a magnet for people to write bots to spam with, and that's not something I support. This project is usable if you add the signing method yourself and also serves as a starting point for someone wanting to create something similar. If you have a legitimate use case, DM me on Twitter and I'll give you some help.

It's of course up to you, adding a signing algo to your code. But you have published the musically API wrapper to NPM, which means it is for everyone, nonetheless.

Secondly, every method (at least as I've observed it) requires their own mas/as/ts combination. So, when you create a TikTokAPI instance, you can use only one method, i.e. you can un-follow a user with this instance, but you cannot follow the user with the same instance. It does not simplify things. At least the code can be improved if it will have ability to apply your own mas/as/ts parameters in every method, like `follow`, `unfollow`, `likePost`, etc.

I have no intention to offend you, but you have said that your purpose is educational and you do not want to simplify things for bots. As I see from list of methods you have created for the TikTokAPI, you use this strategy for promoting yourself on the platform: 
* get list of last followers of some popular person; 
* follow them all; 
* like few of their videos;
* comment other few videos with something like "cool!", "wow!", etc.;
* wait some time; 
* un-follow them; 
* remove likes;
* remove comments; 
* repeat steps above.

It's a good working strategy, but it is exactly what bots do. So you do not prevent TikTok from spam by hiding signing algo, you are just getting competitive advantage by hiding the algo from any user.

Anyway, you have written a good [Medium article](https://medium.com/@szdc/reverse-engineering-the-musical-ly-api-662331008eb3) about reverse engineering the app, which is better than nothing. Thank you very much for the article.

P.S. @ph1go old musically API is not working from today. The `mus-api-prod-akm.zhiliaoapp.com` server does not exist anymore.

**Comment by szdc** [comment]
@nowm you pass in a `signURL` function to the constructor that is called before every request - this is where you add the dynamic signing logic.  You are not limited to one request per instance like you think.

I could add a wiki page explaining the signing process but this library cannot do it all for you - the requirements for signing at this stage are non-trivial.

**Comment by nowm** [comment]
> I could add a wiki page explaining the signing process but this library cannot do it all for you - the requirements for signing at this stage are non-trivial.

To be honest, I even do not use JS for my purposes. So, any hints will be great (either implementation, or textual description). Right now I'm trying to figure it out from Smali, but if you have something you can share, it could be awesome.

**Comment by nowm** [comment]
Also, if you want, I could create few pull requests to extend the tiktok-api library in exchange to the algo.

**Comment by p4rnicke** [comment]
I'm also interested in the signing algo, not an exact code just what it is doing at least.
We have to support our old musically users now, and the old API/service is down after the merge into TikTok. We are not building spam bots or such.

**Comment by p4rnicke** [comment]
I can only send a message on Twitter if you are following me also. @kardosnicke is mine, I'm following you.

**Comment by p4rnicke** [comment]
I can also offer something in exchange for the algo. We are not building bots or act, just need some info about _our_ migrated musically users...

**Comment by szdc** [comment]
@Pilfer if you're willing to compromise a little and think outside the box you don't have to go so far as to learn the CPU architecture.  I went for this solution instead 😃

**Comment by Pilfer** [comment]
@szdc There's no room for compromise with what I'm doing, unfortunately. I have a pretty good idea as to what you did based on the breadcrumbs you're dropping though (or at least one of the few ways it's possible without digging into native code). I know a few people who did something similar with the v1 app (which used bangcle_*), but I opted to reverse and emulate the entire flow for both speed and consistency.

@p4rnicke There's such a thing as responsible disclosure in the security field. @szdc has outlined a few of the methods in a lovely little package (his typescript is beautiful) and given the user everything they need. What he _didn't_ do was essentially give you his api keys/the app's api keys that will both make this repository a target for legal action (at the very least a C&D) and open up the platform for spam. As he stated there's some super simple ways to get the functionality you desire.

**Comment by scrapewww** [comment]
Is your twitter handle szdc? I would like to DM you as well. My Skype handle is AmbitionPHP

**Comment by szdc** [comment]
@scrapewww it's linked above

**Comment by Tigger2014** [comment]
@szdc Im trying to implement theses myself however my java and js are not particularly good, ive decompiled the apk to pseudo java and from what i can tell it relies on the response from UserInfo, however this seems to be a native method so isnt java, ive followed you on twitter if your able to lend some help, my user is @BiteSizedTechie.

Thanks

**Comment by szdc** [comment]
@Tigger2014 the easiest way would be to look at the [Java Native Interface](https://www.baeldung.com/jni) and think about how you could apply that in this situation.

**Comment by Tigger2014** [comment]
@szdc thanks, you helped me out on Twitter a few weeks ago. Got it sorted :)

**Comment by ValkA** [comment]
decompiled appendAntiSpamParams() in case somebody wants it:

```
  public static n appendAntiSpamParams(n paramn, List<String> paramList, int paramInt)
  {
    String str2 = URLDecoder.decode(paramn.toString());
    Object localObject2 = DeviceRegisterManager.getDeviceId();
    Object localObject1;
    if ((str2.contains("&device_id=")) || (str2.contains("?device_id=")))
    {
      localObject1 = localObject2;
      if (TextUtils.isEmpty((CharSequence)localObject2)) {
        localObject1 = (String)URLRequest(str2).get("device_id");
      }
      String str1 = UserInfo.getUserInfo(paramInt, (String[])paramList.toArray(new String[paramList.size()]), null, (String)localObject1);
      localObject2 = localObject1;
      localObject1 = str1;
      paramn = paramn.newBuilder();
      int i = ((String)localObject1).length();
      if (TextUtils.isEmpty((CharSequence)localObject1)) {
        break label273;
      }
      if (i % 2 != 0) {
        break label242;
      }
      paramList = ((String)localObject1).substring(0, i >> 1);
      localObject1 = ((String)localObject1).substring(i >> 1, i);
      localObject2 = a.getSDK(GlobalContext.getContext(), AwemeApplication.getInst().getAid());
      ((ISdk)localObject2).setSession(m.getSessionId());
      localObject2 = EagleEye.byteArrayToHexStr(((ISdk)localObject2).encode(paramList.getBytes()));
      paramn.addQueryParameter("as", paramList).addQueryParameter("cp", (String)localObject1).addQueryParameter("mas", (String)localObject2);
    }
    for (;;)
    {
      return paramn.build();
      localObject1 = UserInfo.getUserInfo(paramInt, (String[])paramList.toArray(new String[paramList.size()]), null, "");
      break;
      label242:
      d.monitor(str2, paramList, (String)localObject1, (String)localObject2, paramInt);
      paramn.addQueryParameter("as", "a1qwert123").addQueryParameter("cp", "cbfhckdckkde1");
      continue;
      label273:
      d.monitor(str2, paramList, (String)localObject1, (String)localObject2, paramInt);
      paramn.addQueryParameter("as", "a1iosdfgh").addQueryParameter("cp", "androide1");
    }
  }
```

**Comment by p4rnicke** [comment]
That’s the east part. What about the encode in libcms.so.
I’m willing to PAY for a working solution for the antispam parameters.
We do not spam or even log in right now, just retreive some info about our users.

**Comment by ValkA** [comment]
I gave it a few hours just for curiosity. Haven't found anything interesting yet :( Thought about finding same lib com0iled for x86 and use it from JS. Haven't found c sources or compiled for x86

**Comment by Tigger2014** [comment]
> That’s the easy part. What about the encode in libcms.so?
> I’m willing to PAY for a working solution for the antispam parameters.
> We do not spam or even log in right now, just retreive some info about our users.

The easiest way to get around the libcms.so is to use that library in your own implementation on android, ive got this working myself so its certainly possible, android x86 and libhoudini might help you out

**Comment by Tigger2014** [comment]
> I gave it a few hours just for curiosity. Haven't found anything interesting yet :( Thought about finding same lib com0iled for x86 and use it from JS. Haven't found c sources or compiled for x86

Just a heads up, there is no x86 version of this library plus is relies on native android calls so it would need a fair amount of the underlying android system

**Comment by p4rnicke** [comment]
I’m not using Android. 
I was using the api from C# on windows server.
tiktok runs also on iOS so there should be a source somewhere for the encrypt.

**Comment by Tigger2014** [comment]
I wrote a web api for an android vm which processes my anti spam bits and then hands it back to my app, which was using python on a windows box. I guess there are multiple way to crack a nut

**Comment by szdc** [comment]
@ValkA as a reminder please don't upload code snippets you don't own.

**Comment by szdc** [comment]
I've added a [wiki page](https://github.com/szdc/tiktok-api/wiki/Generating-anti-spam-parameters) to summarise the discussion here - please feel free to add/edit it.

**Comment by ValkA** [comment]
Strange, trying to include the .so file in a new Android Studio project, finally after getting rid of "not found JNI implementations" getting the following error after calling `System.loadLibrary("cms");`:

`java.lang.UnsatisfiedLinkError: JNI_ERR returned from JNI_OnLoad in "/data/app/com.******.********-*********==/lib/arm/libcms.so"
`
<project root folder>/app/src/main/jniLibs/armeabi-v7a/libcms.so

**Comment by szdc** [comment]
@ValkA you'll need to make sure the package structure for your JNI classes is consistent with the Android app:
`com.ss.android.common.applog` for `UserInfo`
`com.ss.sys.ces` for encoding methods

**Comment by ValkA** [comment]
missed the `com.ss.sys.ces` package, after manually rewriting the correct .smeli file into a .java file it runs :)

**Comment by p4rnicke** [comment]
@Tigger2014 (or anyone) can you help me with a ready solution? I’m not really familiar with JNI and Android :(
I can offer some compensation for your efforts. I have to solve it before I got fired.
My twitter is @KardosNicke

**Comment by p4rnicke** [comment]
Is there anyone who can help me with the java code implementing the web api that runs on Android VM?

**Comment by dixakman** [comment]
> Я написал веб-api для android vm, который обрабатывает мои антиспамовые биты, а затем передает его обратно в мое приложение, которое использует python в окне окна. Я думаю, есть несколько способов взломать гайку

Can you provide the code?

**Comment by dixakman** [comment]
> I wrote a web api for an android vm which processes my anti spam bits and then hands it back to my app, which was using python on a windows box. I guess there are multiple way to crack a nut

Can you provide the code?

**Comment by Tigger2014** [comment]
> > I wrote a web api for an android vm which processes my anti spam bits and then hands it back to my app, which was using python on a windows box. I guess there are multiple way to crack a nut
> 
> Can you provide the code?

As already stated by @szdc posting the code, of any implementation defeats the purpose of the anti spam setup, so for that reason and to respect the hard work of @szdc  I will not be sharing my code. However people are prepared to help when you get stuck and to point you in the right direction.

**Comment by Tigger2014** [comment]
> Got it. Tell me, can the antispam parameters be decrypted back?
This isnt something ive ever tried to do, i just used the library to generate them for me, no decrypting on the values

**Comment by ValkA** [comment]
I've managed to create cp and as params but they a bit different than expected. Can you give a hint how you inited the UserInfo lib? Found some string and int for initing but not sure if thats enough..

**Comment by dixakman** [comment]
Can you throw a project that compiles?

**Comment by Tigger2014** [comment]
> I've managed to create cp and as params but they a bit different than expected. Can you give a hint how you inited the UserInfo lib? Found some string and int for initing but not sure if thats enough..

I believe them being a bit different is not a major issue.
With regards to the init of UserInfo: you need to look for 2 key pieces of info, the appid and the string that is passed to initUser, both of theses can be found within the source code.

**Comment by Tigger2014** [comment]
> Can you throw a project that compiles?

Can you reword that a little, unclear what your asking

**Comment by dyar95** [comment]
> > I've managed to create cp and as params but they a bit different than expected. Can you give a hint how you inited the UserInfo lib? Found some string and int for initing but not sure if thats enough..
> 
> I believe them being a bit different is not a major issue.
> With regards to the init of UserInfo: you need to look for 2 key pieces of info, the appid and the string that is passed to initUser, both of theses can be found within the source code.

I've managed to create both cp and as (they're just the two halves of the getUserInfo() method. I'm stuck on the mas parameter though, did you ever figure that out?

**Comment by ValkA** [comment]
Ive decompiled the apk with jadx and found the use in no time. The encode is a call to one of the jni's.

**Comment by dixakman** [comment]
> > > I've managed to create cp and as params but they a bit different than expected. Can you give a hint how you inited the UserInfo lib? Found some string and int for initing but not sure if thats enough..
> > 
> > 
> > I believe them being a bit different is not a major issue.
> > With regards to the init of UserInfo: you need to look for 2 key pieces of info, the appid and the string that is passed to initUser, both of theses can be found within the source code.
> 
> I've managed to create both cp and as (they're just the two halves of the getUserInfo() method. I'm stuck on the mas parameter though, did you ever figure that out?

Can you share the code?

**Comment by Tigger2014** [comment]
> Can you share the code?


As already stated in my previous reply 
As already stated by @szdc posting the code, of any implementation defeats the purpose of the anti spam setup.
However people are prepared to help when you get stuck and to point you in the right direction.

@szdc  has made it clear he would prefer people not to share their implementations here, please stop requesting people to do so.

**Comment by szdc** [comment]
I'll do a better write-up on the wiki for this, and I'm locking this thread until it's done.

**Comment by szdc** [comment]
Closing as this project is no longer maintained.
