### ISSUE TITLE
Pagination of listPostsInHashtag method

### ISSUE THREAD

**Issue by racinmat** [szdc/tiktok-api#91]
Hi, is there any way to paginate the `ListPostsInHashtag` method?
I see there is `count` parameter which is upper bound for number of returned videos (it never returns the same number of videos as specified in `count`, but smaller amount). And in [this issue](https://github.com/szdc/tiktok-api/issues/69) you mentioned posiibility for pagination using `max_cursor` which allows you to select biggest timestamp you want in returned videos.
But for `ListPostsInHashtag` the results are not chronological, so I would miss some results using the `max_cursor`. 
E.g. on this endpoint `https://api2.musical.ly/aweme/v1/challenge/aweme/?ch_id=2128154&count=30....` results are not chronologically sorted and thus there is no way to paginate them properly.
Is there any way to either enforce the sorting to correctly use the chronological pagination, or any different way for pagination?

**Comment by szdc** [comment]
`ListPostsInHashtag` uses `cursor`, which you use to skip results.  For example, if you retrieve the first 10 results with `count = 10` and `cursor = 0`, you can get the next 10 results by setting `cursor = 10`
