### ISSUE TITLE
Login with unicode chars broken

### ISSUE THREAD

**Issue by urbans** [szdc/tiktok-api#92]
I encountered an issue trying to log in with my username that contains unicode characters. It seems unicode chars are encoded differently than plain ascii, which gives me "User does not exist" error.

After some research it appears that xor encryption just uses a different key (many different keys, actually) for non-ascii chars. For example, When I try to log in with my name in mixed ascii+Russian letters, Tiktok app XORs ascii with key=5, so "u" becomes "70". But a non-ascii letter "ж" in the same string is encoded as "d5b3". Using the key=5 would encode "ж" as "433". 

I tried playing with XOR and found that keys "53445" and "53637" seem to work for different parts of Russian alphabet, but this seems to be dynamic, and is probably based on the unicode codepoint. Has anyone else encountered that issue? Does anyone have a solution?

**Comment by szdc** [comment]
Closing as this project is no longer maintained.
