### ISSUE TITLE
Captcha is empty

### ISSUE THREAD

**Issue by SerAvr** [szdc/tiktok-api#93]
Hi,
When I trying login I have a error "Verification code is empty, please enter the verif..."

![error](https://user-images.githubusercontent.com/48628427/54479724-f22a4f80-4830-11e9-893c-a96a1e75e2ad.jpg)

How do I enter captcha?

**Comment by szdc** [comment]
There's a [`login`](https://github.com/szdc/tiktok-api/blob/f76f4141f74b498d888a10a7ca29122730033a92/src/index.ts#L92) method you can use that allows you to specify the response to the captcha.

**Comment by SerAvr** [comment]
Thanks. How can I answer to captcha? It's a google recaptcha like this https://developers.google.com/recaptcha/docs/v3 ?

**Comment by alexey-gorshkov** [comment]
> Thanks. How can I answer to captcha? It's a google recaptcha like this https://developers.google.com/recaptcha/docs/v3 ?

You got the code in the captcha field, this is a string base64 image. You can view this image at 
[https://codebeautify.org/base64-to-image-converter](https://codebeautify.org/base64-to-image-converter) or generate this image on your frontend page.

**Comment by klliks-com** [comment]
> > Thanks. How can I answer to captcha? It's a google recaptcha like this https://developers.google.com/recaptcha/docs/v3 ?
> 
> You got the code in the captcha field, this is a string base64 image. You can view this image at
> https://codebeautify.org/base64-to-image-converter or generate this image on your frontend page.


http://prntscr.com/nhlns8

How can i solve manually this captcha while using pure requests? 
'data': {'captcha': '', 'description': '', 'error_code': 1105}, 'message': 'error'}
