### ISSUE TITLE
How to install ARM translation on an Android emulator inside Docker

### ISSUE THREAD

**Issue by timoangerer** [szdc/tiktok-api#94]
What would be the best way to use the .so ARM libraries from the tiktok apk on a server/inside docker? I've managed to make it work with a local genymotion setup using libhoudini, but it won't run inside docker.

Here is a related SO question: https://stackoverflow.com/questions/55334014/how-to-install-arm-translation-on-an-android-emulator-inside-docker

**Comment by szdc** [comment]
You'll have to provide more information, e.g. the error messages you're getting.

Alternatively, you could look at using an ARM Android image rather than an x86 one.

**Comment by Animus2018** [comment]
Hello Jack! I have questions. You can be contacted via twitter? I follow you, my @animus2018gmail.

**Comment by szdc** [comment]
Closing as no response received.
