### ISSUE TITLE
Where on earth is libuserinfo.so?

### ISSUE THREAD

**Issue by charlieAndroidDev** [szdc/tiktok-api#95]
I've got a long way through reversing the APK but I cannot for the life of me find the `libuserinfo.so` file anywhere, it doesn't exist in the `/lib` folder or in the `libso` folder in `/data/data`.  I'm fairly confident in reversing the ARM assembly but I can't even find the library!  I've looked at the smali code to see where it's loaded but no dice so far, I wont give up but any help is appreciated.  I might whip up a quick xposed hook and see what actually happens.

**Comment by szdc** [comment]
I haven't looked recently but what makes you think there is a `libUserInfo.so` library? The methods could be contained in another library.

**Comment by charlieAndroidDev** [comment]
Well I've hooked the `UserInfo.getUserInfo()` method and it looks like it is called multiple times and there are parameters passed in, but it always returns null.  Also the app calls `System.loadLibrary("userinfo")`, yet in the logs I can see that each time this is attempted, it fails saying the lib cannot be found.  So maybe you're right and the lib doesn't exist anymore.  Also I've found that if `UserIno.getUserInfo()` is null or empty, then the `mas` parameter is just the encoding of a substring of the `deviceId`.

**Comment by charlieAndroidDev** [comment]
Scratch that, I think all the userinfo stuff is in `libcms.so`, but it seems it's encrypted or they use `RegisterNatives` to further obfuscate their stuff.  I'm almost there, I might have to do some dynamic analysis of the native lib instead of just static.

**Comment by charlieAndroidDev** [comment]
I found a Chinese article with the `getUserInfo` implementation, though it was outdated but not by very much.  After dynamic analysis of `libcms.so` I have found the keys and the `rstr` needed for the `getUserInfo` function to work, but not sure how the implementation/algorithm itself has changed.

**Comment by charlieAndroidDev** [comment]
I know no-one is replying but I'll use this to track my progress.  I've got the new algorithm for AS+CP now, still need to figure out how to generate the 4 digit string that is appended to `as` and the 4 character string appended to `cp` but basically there.  After that I just need to find the encode method in `libcms.so` for the `mas` parameter.

**Comment by owen800q** [comment]
> getUserInfo()
I use VirtualXposed to hook getUserInfo, but not working at all but when I hooked inituser, it works
May you share some details how to hook getUserInfo

**Comment by charlieAndroidDev** [comment]
I hooked `getUserInfo` with an Xposed module that I wrote.  It's very basic.

**Comment by klliks-com** [comment]
> I hooked `getUserInfo` with an Xposed module that I wrote. It's very basic.

I am getting:
'data': {'captcha': '', 'description': '', 'error_code': 1105}, 'message': 'error'}

For each account i try to login. Any idea how to bypass/solve it?
