### ISSUE TITLE
Cant get install and device id

### ISSUE THREAD

**Issue by Riyaz7364** [szdc/tiktok-api#96]
Hay i try to get install and device id using PHP
But its always return 
```
{
    "server_time": 1554876434,
    "device_id": 0,
    "install_id": 0
}
```
I simply use Register URL to get details

> http://applog.musical.ly/service/2/device_register/?mcc_mnc=40411&app_language=en&language=en&region=US&sys_region=US&carrier_region=IN&carrier_region_v2=404&build_number=10.1.9&timezone_offset=19800&timezone_name=Asia%2FKolkata&is_my_cn=0&fp=&pass-region=1&pass-route=1&ac=wifi&channel=oppo_int&aid=1233&app_name=musical_ly&version_code=100109&version_name=10.1.9&device_platform=android&ab_version=10.1.9&ssmix=a&device_type=CPH1809&device_brand=OPPO&os_api=27&os_version=8.1.0&openudid=68f322e0f4922f15&manifest_version_code=2019030209&resolution=720*1424&dpi=320&update_version_code=2019030209&_rticket=1554875916651&tt_data=a

and also use same Header but result always same. Help me to get this details

**Comment by charlieAndroidDev** [comment]
Your _rticket looks pretty old.  Use a current timestamp for the _rticket and try again.

**Comment by Riyaz7364** [comment]
> Your _rticket looks pretty old. Use a current timestamp for the _rticket and try again.

I try with current timestamp [ time() ] function bust result still same.

**Comment by Riyaz7364** [comment]
> Your _rticket looks pretty old. Use a current timestamp for the _rticket and try again.

I try with current timestamp [ time() ] function bust result still same.
I try in mitmproxy 
edit _rticket value to 0 then hit replay but then i got ids. i dont think that is the problem.

**Comment by szdc** [comment]
Not supported by this API at this time.
