### ISSUE TITLE
'data': {'captcha': '', 'description': '', 'error_code': 1105}, 'message': 'error'}

### ISSUE THREAD

**Issue by klliks-com** [szdc/tiktok-api#97]
Hi Guys

It seems like TikTok Turned on captcha for each account login.
It doesn't matter if i use:
iOS/Android/Emulator/scripts

I have the script for device_id and install_id.
So i need to find a way to solve captcha on login (via API)
It was working couple days ago, it's something new.

I was thinking about:
1. Integration with captcha solver
2. Send captcha to my local browser/server and to solve it manually

I would like to know which option is the best?
Are you guys have a built-it solution for login+captcha solve.

Thanks

**Comment by umeshdepale** [comment]
Hi I have an issue in device id I got an error like - 

 stdClass Object ( [data] => stdClass Object ( [captcha] => [description] => You are visiting our service too frequently. [error_code] => 7 ) [message] => error )

if I try to login can you help me to solve this issue

**Comment by Pilfer** [comment]
@klliks-com 1105 is the captcha code it expects a solution for on the next call (the puzzle slider one).

**Comment by Pilfer** [comment]
@umeshdepale rate limiting is a thing. don't be dumb.

**Comment by klliks-com** [comment]
> @klliks-com 1105 is the captcha code it expects a solution for on the next call (the puzzle slider one).

I understand. 
If captcha is solved then everything is good. 
But What are my options to solve/bypass puzzle slider?

**Comment by klliks-com** [comment]
@Pilfer moreover is there a service that can solve this captcha via api? or is there a way to solve it manually? or bypass ?

It was working good for me, but then accounts logged out and now each login ask captcha.
so i want to solve captcha and keep session alive. because if accounts logged in they can work for long time.

**Comment by umeshdepale** [comment]
But How to solve 1105 error I use PHP for this coding link- https://coding.vivoliker.com/OLP95IXSOo is anyone helps me to solve captcha issue

**Comment by szdc** [comment]
@umeshdepale see [this answer](https://github.com/szdc/tiktok-api/issues/93#issuecomment-473708678).
@klliks-com solve the captcha manually, this repository isn't the place to discuss captcha automation.

**Comment by klliks-com** [comment]
> @umeshdepale see [this answer](https://github.com/szdc/tiktok-api/issues/93#issuecomment-473708678).
> @klliks-com solve the captcha manually, this repository isn't the place to discuss captcha automation.

All good. I would like to solve it manually. How can i do it?
I used QtWebView but impossible to move fragment probably touch events are not emulated.

I need a way to solve it on same server.
Please assist.

**Comment by szdc** [comment]
@klliks-com the image is base 64 encoded - see the answer linked above.

**Comment by klliks-com** [comment]
I sent you DM on twitter, also on skype.
I need help with this one. i am willing to pay if needed.

I still don't understand how to solve it manually.

**Comment by klliks-com** [comment]
> @klliks-com 1105 is the captcha code it expects a solution for on the next call (the puzzle slider one).

Can i have your email/skype please?

**Comment by klliks-com** [comment]
> @klliks-com the image is base 64 encoded - see the answer linked above.

I don't get regular captcha.
It's puzzle captcha which detect be if i am not real user.

Please don't delete my messages, i need help to understand how to solve captcha manually.

**Comment by umeshdepale** [comment]
Hi, @klliks-com I got the same issue Is anyone here who help and hello @klliks-com can you share login code with me

**Comment by klliks-com** [comment]
I know that many people using same API are able to login and solve captcha.
Anyone can explain clearly how to do it?

**Comment by umeshdepale** [comment]
Can you share your login code @klliks-com

**Comment by umeshdepale** [comment]
Which Language you use for login PHP or other ?

**Comment by klliks-com** [comment]
> Which Language you use for login PHP or other ?

Python.

**Comment by umeshdepale** [comment]
ok can you send me python file I use PHP

**Comment by klliks-com** [comment]
> ok can you send me python file I use PHP

I am here to understand how to solve captcha manually. only reason.
I have no problem to pay for this. but i need explanations.

**Comment by umeshdepale** [comment]
I Have the same problem but I have API in PHP not in python if you help me to give python code so it's help me lot
